### ISSUE TITLE
www.d.tube is not redirected properly

### ISSUE THREAD

**Issue by vinyll** [dtube/dtube#1]
The subdomain [www.d.tube](https:///www.d.tube) is not redirecting properly to d.tube.

I ended up on this URL from some link, I can't remember from where

**Comment by damiantoczek** [comment]
There is a DNS issue with it. The owner of d.tube must fix that.
![ovh dns](https://user-images.githubusercontent.com/24800374/52728268-3d91d980-2fb7-11e9-9037-b4b91e31562e.png)
There is no redirection from www.d.tube to the /www (or what ever) folder.

**Comment by skzap** [comment]
The use of the www subdomain is redundant and time consuming to communicate. We are better off without it
