### ISSUE TITLE
I have a weird Ui bug 

### ISSUE THREAD

**Issue by steeminator3000** [dtube/dtube#109]
I'm facing a weird UI glitch after the first patch in Chrome Browser

Google Chrome is updated
76.0.3809.100 (Resmi Derleme) (64 bit) Sürümü

![image](https://user-images.githubusercontent.com/33560676/62832967-beb4eb00-bc3f-11e9-8508-89083e5adecc.png)

**Comment by skzap** [comment]
Bug was introduced recently, working on it

**Comment by skzap** [comment]
Fixed in https://github.com/dtube/dtube/commit/b573ac0df1cca36579209b287a4f0475467f2961
