### ISSUE TITLE
Check for validity of announced IP of Avalon node leader

### ISSUE THREAD

**Issue by kekkyojin** [dtube/dtube#110]
DTube Avalon uses leaders which are the equivalent to Steem witnesses. They are listed on their own section. Those leaders should add their own IP -or hostname- so other nodes are able to connect to them. When hover the mouse over a leader which has provided an URL, the UI shows it as a tooltip.

It is currently not checking for the IP address to be a valid one. Web page will show that leader as enabled -not grayed-.

**Comment by techcoderx** [comment]
Avalon has `ENABLE_NODE` transaction since testnet v2, which enables/disables a leader by adding or removing a leader key instead of using an announced IP in JSON profile.
