### ISSUE TITLE
Streaming Quality : Unable to Set

### ISSUE THREAD

**Issue by maheshkay** [dtube/dtube#112]
If you open any video on D.tube you may find that gear icon for setting in the player allows you to set the quality of video. 

So assuming you have option like 240, 480, etc. If the default value selected by the player is 480. You can't set the value below that. For example if I select the value to 240. It gets reset to 480. 

This behavior has nothing to do with any extension. As I have tried this with disabled extension and also tested in Incognito mode. 

Following is my browser:
Chrome: Version 76.0.3809.100 
Internet Connection Speed: 1 mb/s

**Comment by techcoderx** [comment]
Takes time for it to update when it loads the new selected resolution
