### ISSUE TITLE
tokensale bad access

### ISSUE THREAD

**Issue by Kwaskoff** [dtube/dtube#115]
1. App ask me make testnet account
- ok
2. App ask me verification by sms, fb and email
- ok. email, fb, sms. done
3. App congratulated me:
Welcome @fintechassociation2019, you are now a DTuber.
Warning: you now own a testnet account. This account will not be ported to the main-net automatically unless you are an airdrop recipient or a token sale investor. 
Your channel is publicly accessible on https://d.tube/c/fintechassociation2019
- ok. go to https://signup.d.tube/sale.html and authorization
Could not find account @fintechassociation2019
look at screen!! 
![https://imgur.com/cY6QTEf](https://i.imgur.com/cY6QTEf.png)

**Comment by tibfox** [comment]
The problem has been the @ in front of your username @Kwaskoff
