### ISSUE TITLE
Unable To Save Profile On D.Tube Channel

### ISSUE THREAD

**Issue by BJTMastermind** [dtube/dtube#118]
When I change my channel about info and click Save Profile nothing happens nothing gets saved and I don't get any error messages making it currently impossible for me to add a channel cover image or anything else.

**Comment by tibfox** [comment]
I can save my profile. Do you receive any erros when you hit save? Do you really have a DTube account and signed in? @BJTMastermind

**Comment by BJTMastermind** [comment]
No i don't get any errors when i click save. Yes, I signed up using Steemit if that matters.

**Comment by skzap** [comment]
Is this still an issue? It's probably related to caching? i.e. changes take 10 minutes to appear?

**Comment by techcoderx** [comment]
Closing this for now, if the issue still persists please reopen
