### ISSUE TITLE
Cannot register on d.tube

### ISSUE THREAD

**Issue by gloschtla** [dtube/dtube#119]
JSON error message: 

_The security token included in the request is invalid_

_InvalidClientTokenId_ 

https://signup.d.tube/

**Comment by lrq3000** [comment]
Same here, please see also the more complete description of the error message here:

https://www.reddit.com/r/dtube/comments/edbs0n/i_cant_sign_up/

**Comment by lrq3000** [comment]
Additional details: This error "the security token included in the request is invalid" is just after the Google reCaptcha, which for some reason always fails with this error.

**Comment by DarthVanger** [comment]
Duplicates: #127, #134
