### ISSUE TITLE
When adding a user check if name already in collection

### ISSUE THREAD

**Issue by kirkins** [dtube/dtube#12]
I noticed that by accident at one point I'd added my same account 5 times.

Would it be possible to check if the user already exists in the collection before adding it again?

![user](https://user-images.githubusercontent.com/9503662/40812256-e0a0cddc-6502-11e8-98c7-14aacbab6d83.png)

**Comment by kirkins** [comment]
Related code

https://github.com/dtube/dtube/blob/f6c9fe5c271f9bd552b8431a89a48bfd4824f23c/client/views/pages/login/login.js#L19-L26

**Comment by kirkins** [comment]
Looks like it is fixed when I run locally.

**Comment by techcoderx** [comment]
Multi-account login with the same network has been replaced with multi-network login since the addition of Avalon and Hive
