### ISSUE TITLE
Offer DTC for all videos according to how good they are

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/dtube#124]
Inspired by Vigo's flames

**Comment by tibfox** [comment]
DTube has a curation team who decides this in objective manners. So I dont think there should be an issue for that here

**Comment by DaniellMesquita** [comment]
@skzap I mean, it could be a premise like it is used in Vigo. Users already knowing good videos and participating in challenges will made them earn DTC (like flames). Video thumbnail could also display it.
