### ISSUE TITLE
Organize contests for the community

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/dtube#125]
DTube team will publish a challenge (example cook a 🎂 video) and users does a video with this topic.

It will also have a section w
in home page with their trending videos.

**Comment by tibfox** [comment]
To run such a contest is a task for the node leaders or the communities in my opinion. 
But displaying the challenges / contests is a good idea I think

**Comment by skzap** [comment]
I really don't think the DTube team (running the UI available on d.tube) should influence what displays on the UI. SteemIt for example has a 'pinning' feature controlled by their staff which I really dislike overall, and creates an unfair advantage that could lead to corruption.

However I'm totally okay with funding useful contests (maybe dtube turorials) created by the community

**Comment by DaniellMesquita** [comment]
> I really don't think the DTube team (running the UI available on d.tube) should influence what displays on the UI. SteemIt for example has a 'pinning' feature controlled by their staff which I really dislike overall, and creates an unfair advantage that could lead to corruption.

Yes, I agree. That gave me a flame discussion against LBRY developers on Slack in 2016. Handpicking content by the host is what YT already does.

> However I'm totally okay with funding useful contests (maybe dtube turorials) created by the community

1. Any user can propose a challenge of the week
2. Users votes in the challenge they most likes
3. The most voted/curated is officially choosen as the challenge of the week

**Comment by skzap** [comment]
Testnet distribution is totally wrecked. Some bots (yummyrecipe, alpayasteem, cartoonworld) is running a voting ring which generated a big amount of DTC. I think probably the team can decide the winner out of the most voted ones. I think @steeminator3000 should organize it, he's already managing the curation side of things.

**Comment by techcoderx** [comment]
Closing this as we have the mainnet, there are contests that are being organized such as @tibfox's #originaldtuber initiative. There are probably more that will be announced in #contest-announcements on the [Discord server](https://discord.gg/dtube).
