### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/dtube#130]

**Comment by skzap** [comment]
What do you mean?

**Comment by DaniellMesquita** [comment]
Are the production app export folder, when being compiled, have the same hash?

**Comment by skzap** [comment]
builds are basically the dtube/production repo. I only build the .js and .css from dtube/dtube repo and put them in there.

**Comment by DaniellMesquita** [comment]
If at same hour you do this build twice without any modification in source files, do it maintains same hash? If yes, these are reproducible builds.

**Comment by skzap** [comment]
Yes, the hash of the builds depends on the source code. Same source javascript => same hash.

**Comment by skzap** [comment]
That's how meteor works
