### ISSUE TITLE
Enable merging of YouTube+IPFS videos

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/dtube#132]
In my channel, there are a dupliced video, in IPFS and YouTube. https://d.tube/#!/c/mesquita
It could be considered one video; showing icons (DTube, YouTube, Facebook) pointing where this video is. Also, option to do it for other videos (uploading to DTube or linking to other network).

**Comment by DaniellMesquita** [comment]
@skzap

**Comment by skzap** [comment]
Feature is available for testing on https://sta.d.tube

**Comment by DaniellMesquita** [comment]
Yes, it works even for dupliced videos in the same platform, as also in others.

But it could be more semantic. For example, show in description its dupliced versions and also icons for other platforms the same video is (YT, Dailymotion, Facebook).

**Comment by DaniellMesquita** [comment]
Hey. At my profile (mesquita) it does yet haves dupliced videos. Is this update applied to the main?

**Comment by techcoderx** [comment]
Yes, it's already live. You can see the logos at the top-right corner of the player when you hover over it, for example https://d.tube/v/techcoderx/Qmf4DzZbb8uN5Ld1cgHJQvMXj3TPYQRsSLVU6KJhA8ze9b

**Comment by skzap** [comment]
It's also in the (...) menu (for mobiles who cannot 'hover').

But I'm still unsure if the feature should be in the UI (d.tube) or in the player (emb.d.tube). My main concern with putting it in the player, is that once redirected to youtube, there's no way to go back...

**Comment by DaniellMesquita** [comment]
Its about channels/profiles. There are yet dupliced videos, unlike the demo you have previously shown.

https://sta.d.tube/#!/c/mesquita
