### ISSUE TITLE
Declare videos as original content

### ISSUE THREAD

**Issue by techcoderx** [dtube/dtube#137]
As Steem mostly only tolerates original content, it may be necessary to have authors to declare their videos as original content. If not declared, the video may not be posted on Steem, or have the STEEM payouts declined/sent to @null as beneficiary.

This may be useful in several ways:
1. Allow filtering in UI to show only original contents
2. Allow only videos declared as original to be curated with curation bot

Videos that are wrongfully declared as original may risk getting downvoted.

**Comment by DaniellMesquita** [comment]
It is depending in the kindness of video uploaders. What about a voting, like the tags?
