### ISSUE TITLE
Uploaded video doesn't show in the search results

### ISSUE THREAD

**Issue by MetallianFR68** [dtube/dtube#14]
I uploaded a video several days ago
https://d.tube/#!/v/metallian/za3m7s10

The title contains "LEGO" and I added "LEGO" as a keyword, but it never displays when searching for LEGO

Why is that ?

**Comment by MirceaKitsune** [comment]
I can confirm this issue: Even if a video contains a word in its title or its description or its keywords, that video may still never show up in searches when searching for that word. It feels to me like search is highly broken at the moment, and I'm curious as to when and how this can be solved.

**Comment by skzap** [comment]
search has been fixed on v0.9, our new blockchain supports elastic search mirroring through 'monstache'.
