### ISSUE TITLE
Design change of login buttons

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/dtube#141]
- [x] Only a "Login" button
- [x] When logging in a choosen blockchain, instead of redirecting to start page, 
~~change tab menu focus, offering login in other network~~
return to the page the user was on before going to /login
- [x] After logged, in place of "Login" button, user photo/name with icons of which networks are connected. These icons have sub-icons (checkmark or a X) telling if logged, and clicking these icons opens login popup with focus in the tab about the selected

Actually showing dupliced user info and buttons is pretty confusing. The problem is if user uses different info in Steem and Avalon. It will require a sync feature for uniformity.

**Comment by skzap** [comment]
I agree. The current 'login zone' on top of the left side menu is ugly and distracting. 100% okay for just a 'login' link that takes you to page where you see available login methods + current logged in users.

It's a pretty easy change I believe.

The redirect should not work the way you described I think. I don't think it should go to home page either, I think it should go back to the page last visited before the login button. Maybe user was on a video page, tried to vote, noticed he wasnt logged in, logged in. Then he should be taken back to the video he was watching

**Comment by skzap** [comment]
I guess only thing left is redirecting to the 'page before login' after a succesful login, instead of blindly to the homepage.

I believe it's not so critically important but it would improve the ergonomy
