### ISSUE TITLE
node selection will not get reseted after removing nodes from the available node list

### ISSUE THREAD

**Issue by tibfox** [dtube/dtube#147]
When the team removes bad nodes (in my case it was anyx.io under the steem node settings) the page does not reset the selection. It will still use the old selection and tries to use it for posting. The selection is just not set: 

![grafik](https://user-images.githubusercontent.com/6019754/78455599-8b780e00-769f-11ea-9fde-ca3aca2bc0d8.png)

This will result in a bad execution and in my case it tried to post 2x on hive (since anyx.io is now a hive node): 

![grafik](https://user-images.githubusercontent.com/6019754/78455591-84510000-769f-11ea-84aa-0b531ef2a3de.png)

**Comment by skzap** [comment]
Fixed in https://github.com/dtube/dtube/commit/90f0017d3584788da08a41cf9305585a954d5fa7
