### ISSUE TITLE
Integrate with Plentyofphish

### ISSUE THREAD

**Issue by gryter** [dtube/dtube#15]
https://github.com/gryter/plentyofphish

OR

"Mutes" by https://steemit.com/@plentyofphish

The entire list of hacked/phished accounts (under hacker control) is held both in the repository and on the blockchain in the mutes. List is kept up to date to the best of our ability.

**Comment by techcoderx** [comment]
We now have Avalon as the main network, with Steem and Hive being the additional networks supported. So using official blacklists are not necessary where just downvotes would do
