### ISSUE TITLE
The settings button below the video does not work while the video is playing

### ISSUE THREAD

**Issue by Icramss** [dtube/dtube#16]
- Open dtube https://d.tube
- Sign in with your account steem
- Upload your video (link video and subtitle video tumbhnails)
- Once you've finished uploading, try playing that video.
- when the video is playing, Tap on the settings icon under the video. It does not work

**Comment by Icramss** [comment]
You can see my recording.

https://youtu.be/t64jxip_-Dw

**Comment by techcoderx** [comment]
Shouldn't be an issue anymore after multiple updates to the embed player
