### ISSUE TITLE
Curation and Voting doesn't make sense in the UI

### ISSUE THREAD

**Issue by steeminator3000** [dtube/dtube#162]
I personally think its a little bit hard to navigate through interface when you are curating content , it is really hard to understand what is happening behind the scenes when you vote a video. A slider and changing earned reward numbers after you vote would be a really nice addition. Because it feels like nothing is happening after you vote a content.

![image](https://user-images.githubusercontent.com/33560676/84512303-75ef1800-acd0-11ea-8f46-8e934007276b.png)

**Comment by techcoderx** [comment]
Vote sliders added in v1.0 patch
