### ISSUE TITLE
[feature request] delete account

### ISSUE THREAD

**Issue by chiboreache** [dtube/dtube#165]
!

**Comment by techcoderx** [comment]
As data stored on the blockchain is immutable, it is not possible to delete blockchain accounts.

**Comment by chiboreache** [comment]
i can't create new account, it always log in me to existed one, clearing cookies doesn't helped on vivaldi 

chromium seems to work

**Comment by chiboreache** [comment]
fannoying as hell, i have to use another email now

**Comment by skzap** [comment]
@chiboreache it's by design. We only give 1 free account per email address on signup.d.tube
