### ISSUE TITLE
[feature request] username != channel name

### ISSUE THREAD

**Issue by chiboreache** [dtube/dtube#166]
wtf???

**Comment by techcoderx** [comment]
Do you mean adding a separate channel display name?

**Comment by chiboreache** [comment]
when you creating account, you have field called username, but then blah-blah congraz - you created %username% channel


and after it you have to f****** deal with it, use new email to fix that s*** and so on and so forth

**Comment by chiboreache** [comment]
**extremely annoying**

**Comment by chiboreache** [comment]
YT way much more liberal in that term

one acc, many channels

**Comment by techcoderx** [comment]
I understand your frustration. Right now DTube chain is still a testnet, so only the account "dtube" can create new accounts. When the mainnet starts, anyone can burn DTC to create new accounts without any verification. I do not have any information on when the mainnet will launch as there are still bugs to be fixed.

**Comment by techcoderx** [comment]
Mainnet is live, so anyone can burn DTC to create new accounts.

If you have any issues with this matter please reach out on our [Discord server](https://discord.gg/dtube).
