### ISSUE TITLE
Chrome upload page issue

### ISSUE THREAD

**Issue by steeminator3000** [dtube/dtube#168]
![image](https://user-images.githubusercontent.com/33560676/89921240-19dc3d80-dc06-11ea-8322-e629fd5d6f26.png)

 getting single tag is allowed error eventhough its single tag. Chrome  Version 84.0.4147.125 
![image](https://user-images.githubusercontent.com/33560676/89921142-fb764200-dc05-11ea-8d7b-215fef458344.png)

All the plugins disabled and tried uploading again still got the same error and screen got completely frozen.

I tried uploading with Edge browser it worked.

**Comment by techcoderx** [comment]
Probably related to the tags field issue, might possibly replace the dropdown with an ordinary text field that always worked before

**Comment by techcoderx** [comment]
fixed [here](https://github.com/dtube/dtube/commit/0360ef4ca67299bf4298225c18c138ffb9652d84)
