### ISSUE TITLE
Make the VP amount spent shown in thumbnails look less like likes.

### ISSUE THREAD

**Issue by strobili** [dtube/dtube#170]
I am a novice when it comes to using D.Tube, and so I was very confused when a website that only gets ~500,000 monthly visitors (from what I have been told) has videos uploaded less than a week ago that have millions of likes. Turns out, these were not likes, but rather the amount of VP spent on the video.

I think that this should be changed, as it temporarily caused me to think the website was intentionally lying, and that is not something you want someone who views your website for one of the first times to think. Right now, the way the amount of VP spent on a video is represented is by a thumbs up and a number followed by the letter "M." For most people, they will assume these are likes, as this is very similar to the way YouTube does it, which is where most people come from.

**Comment by skzap** [comment]
Agreed, it's confusing for users.

If you check the HOT or TRENDING category, we can see we already introduced a small change to make it clearer, but it didn't apply to the whole site yet.

Not every vote is worth the same on DTube, and it's possible for 1 large vote to overcome thousands of small ones, so this number will remain somewhere, but I agree, it's confusing for users. The next patch will add more control over your VP (with a vote slider), so hopefully we can stick to displaying total number of accounts who voted, and keep the total VP somewhere more hidden in the UI

**Comment by techcoderx** [comment]
fixed in #249
