### ISSUE TITLE
Rotation screen bug on Dtube android app

### ISSUE THREAD

**Issue by ashiqurakash** [dtube/dtube#18]
#### Expected behavior
While watching a video in landscape mode user should be able to search in landscape mode and user should be able to see all the content in landscape mode while the paused video in the bottom left on the screen.
#### Actual behavior
In landscape mode while watching a video user can't search in landscape mode. When user started typing Dtube app go portrait mode automatically but the user was still holding the phone in landscape mode. And also in landscape mode user can't see all the content properly while the video is paused or paying in the bottom left on the screen. 

#### How to reproduce
* Download and install Dtube from [Google play store](https://play.google.com/store/apps/details?id=pro.bostrot.dtubeviewer)
* Login with your Steemit account.
* Play a video in landscape mode.
* To find the bug you need to pull the video on the bottom left of the screen.
* In this situation user won't be able to see all the content of the background in landscape mode while watching a video.
* And also try to search a video in landscape mode.
* A letter box will appear so that you can type and search in landscape.
* But at the very moment when user started to typing Dtube app immediately go portrait and the user couldn't even finish the typing in landscape here. 

* App version: 2.0.3
* Operating system: Android 7.0

#### Recording Of The Bug
https://youtu.be/sETfRaW1wIY

**Comment by skzap** [comment]
DTube doesn’t have a mobile app yet. The one you are using is unofficial and is unrelated to this repo.
