### ISSUE TITLE
dtube isn't  fully decentralized really!

### ISSUE THREAD

**Issue by AnonymousWebHacker** [dtube/dtube#183]
How I can make my own dtube fully decentralized and without dependency of loging on  https://signup.d.tube/ or dependency any web site for dtube work whitout promblems.
I can implement my own https://signup.d.tube/  ?
NO

**Comment by techcoderx** [comment]
The signup code is available here which you can run yourself: https://github.com/dtube/signup

Also you can create accounts yourself with DTC burn at https://d.tube/#!/newaccount, or using [javalon](https://github.com/dtube/javalon):

```
const javalon = require('javalon')

let tx = {
    type: 0,
    data: {
        name: 'newusername',
        pub: 'newpublickey'
    }
}

let signedTx = javalon.sign('yourprivatekey','yourusername',tx)
javalon.sendTransaction(signedTx, (error,result) => {
    console.log(error,result)
})
```

**Comment by AnonymousWebHacker** [comment]
I mean that once I have my dtube service running on my local server (without internet), I need internet to be able to create the accounts. My network is a SNET (street network), I do not have 24 hour internet, (nor users) so that my users can register on the server.

**Comment by AnonymousWebHacker** [comment]
@techcoderx Thank you, I will check the links 👍

**Comment by AnonymousWebHacker** [comment]
https://github.com/dtube/dtube#running-blockchain-locally

**Comment by AnonymousWebHacker** [comment]
@techcoderx With javalon, I can implement so that my users can register without internet?

**Comment by techcoderx** [comment]
Not on the main network, there is no way to connect with peers without an internet connection. Hence it will only work in an offline testnet.

You can have javalon to communicate with your local node with:
```
javalon.init({ api: 'http://localhost:3001' })
```
