### ISSUE TITLE
After claiming rewards, the "Claim X.XX DTC" button is still active

### ISSUE THREAD

**Issue by brishtiteveja** [dtube/dtube#192]
On rewards page on your channel, after you claim rewards, immediately your coin goes up, however the "Claim X.XX DTC" button still shows to claim rewards that have just been claimed. This leads to invalid transaction upon clicking again. It's probably a UI fix.

![Screen Shot 2020-10-09 at 4 13 19 AM](https://user-images.githubusercontent.com/2281405/95559909-7e3d3280-09e6-11eb-8c18-58e25c8ac300.png)

**Comment by skzap** [comment]
It's just a bug related to data-caching. Takes ~1min to update.

**Comment by brishtiteveja** [comment]
Yeah, I figured that. But is there a way to suppress?

**Comment by techcoderx** [comment]
Closing this for now, probably hard to reproduce
