### ISSUE TITLE
Microsoft Edge Login

### ISSUE THREAD

**Issue by BZ2m8** [dtube/dtube#20]
On Edge the login button is disabled after you click on the "Remember me" slider.

Other minor issues:
On a touch screen the settings menu of the player just displays a blank box (tested with Firefox).
No "Show All" button for "Subscribed Feed" or other way to see all videos from your subscriptions.

**Comment by skzap** [comment]
I cannot test this on Edge on my environment. Maybe a windows dev is willing to get this fixed? :)

**Comment by techcoderx** [comment]
Sub feed page was already added [here](https://github.com/dtube/dtube/commit/4e6fb862acaaa59f24ef4e004c1351bdae974a28).

The issue is a bit old, closing it for now. Please recreate it if it still persists.
