### ISSUE TITLE
There should be a hint/information about selfvote VP in uploader

### ISSUE THREAD

**Issue by tibfox** [dtube/dtube#202]
It seems that users don't know the importance of the first vote or they simply forget to set the slider high enough before sending their new video. In the end we have a bad user experience bc they think they can not earn off of their own videos. It would be good to have a little hint / information about this setting in the uploader. In the best case this information only pops up if the selfvote is lower than 50%.

**Comment by tibfox** [comment]
@skzap @techcoderx what do you think? Should we do that?

**Comment by techcoderx** [comment]
Author tip hardfork is live, so creators spending only 1 VP should still be able to earn through tips as long as the author vote is not claimed.
