### ISSUE TITLE
For the past few weeks I get stuck on this screen when "file uploading" a video.

### ISSUE THREAD

**Issue by ColinTalksCrypto** [dtube/dtube#203]
I'm encountering a bug which prevents me from being able to upload new videos. For the past few weeks I get stuck on this screen when "file uploading" a video.

Sometimes after an enormous amount of waiting, a stranger's video (not mine) appears on the next screen.

![Capture](https://user-images.githubusercontent.com/44652168/97801679-d5fd4100-1c14-11eb-911f-0b5cb63bd56a.JPG)

Can you help fix this so I can upload again?

I also shared this question here but received no response: https://twitter.com/COLINTCRYPTO/status/1322658678676328448

**Comment by skzap** [comment]
@ColinTalksCrypto When was your last attempt? I believe this is fixed since yesterday. There was a problem with the IPFS instance running that failed often to add files (anything over XX MB).

But it should be good now? Please let me know. I'm on discord as @heimindanger too.

**Comment by ColinTalksCrypto** [comment]
@skzap Yes, the issue was with IPFS and uploading larger video files.

I am happy to say I'm once again able to upload my videos. Whatever the issue was has been fixed. Thanks.

**Comment by skzap** [comment]
Thanks for reporting back. Closing that now.
