### ISSUE TITLE
Display video length with thumbnails

### ISSUE THREAD

**Issue by mnemnion** [dtube/dtube#205]
Attaching a screenshot to show what I see from d.tube on macOS Safari:

<img width="664" alt="Screen Shot 2020-11-01 at 6 17 37 PM" src="https://user-images.githubusercontent.com/231785/97829645-b98df280-1c6e-11eb-8f4d-48de4dffa8ee.png">

When I browse YouTube, the length of a video plays an important role in deciding whether to watch it. I don't know what the lightning icon or DTC numbers mean, but my guess is "number of views" for the former and "earnings" for the latter? 

In any case, length of the video is the most important statistic, after the title and before the number of likes, for me. There are a lot of topics I'll watch ten minutes on which I won't even want to start a full hour of.

**Comment by tibfox** [comment]
I agree that VP is not rly important bc we already have the DTC underneath the video title. There is a "duration" attribute in the json of "contents" and we could use that to display video length instead of VP. 
If we approve that I can implement that
