### ISSUE TITLE
invalid tx data.vt

### ISSUE THREAD

**Issue by deconDarts** [dtube/dtube#207]
![invalid tx data.vt](https://user-images.githubusercontent.com/68884395/99195280-63c74900-274a-11eb-9c2a-5ac2bba6e72d.PNG)

I haven't returned a search with anything regarding this issue. (https://github.com/dtube/dtube/search?q=data.vt & 'generic web search')

Attempted workaround by "Add Subtitle;" assuming the issue had to do with no subtitle; submit spins 'forever'

Useful if the issue notif could be clicked for insight

(using the provided ipfs.io/ipfs/HASH )

**Comment by techcoderx** [comment]
Error message clarified [here](https://github.com/dtube/avalon/commit/7bba2228b097a7fab01623ccd5939780e1e49089), vote slider should not allow 0 VP to be spent. Frontend patch coming soon.
