### ISSUE TITLE
The resteem button do not work on d.tube mobile website version.

### ISSUE THREAD

**Issue by iamowomizz** [dtube/dtube#21]
**Expected Behaviour**
When i click on the resteem button on the Dtube mobile view, i expect the video to be resteemed on my channel or page.

**Actual Behaviour**
When i click on the resteem button on the Dtube mobile view, nothing happens and the video dosen't get resteemed on my channel or page.

**How To Reproduce**

* Go to d.tube
* Click on any video to watch
* Click on the 3 vertical dots just below of the video by the right hand side
* A drop down shows, click on resteem.
* Then go back to check your page or channel to see if the video has been resteemed, you will find out it hasn't.
* Browser: Phoenix Browser version 3.0.2
* Operating System: Android 7.0 (dtube Mobile website version)

**Recording Of the Bug**
https://youtu.be/xA-z91b9fm0

**Comment by skzap** [comment]
This bug was fixed recently. It will be in the next update.
