### ISSUE TITLE
Why is d.tube hardcoded?

### ISSUE THREAD

**Issue by kgnfth** [dtube/dtube#212]
for example

a href="http://twitter.com/intent/tweet?url=http://d.tube/v/{{author}}/{{link}}" class="popup" target="_blank">
var postUrl = 'https://snap1.d.tube/uploadSubtitle'

**Comment by tibfox** [comment]
This is the snap API part which is currently a separate API. But qwe are going to implement this in the normal Avalon API code so this will change soon

**Comment by kgnfth** [comment]
Ok thx
Great work btw
