### ISSUE TITLE
Green indicator for mining leaders in Nightmode shows first 10

### ISSUE THREAD

**Issue by steeminator3000** [dtube/dtube#214]
![image](https://user-images.githubusercontent.com/33560676/101414141-96520500-38f6-11eb-90c4-4abfc8f83ec2.png)

There is a green color for elected mining leaders on night mode but its only showing first 10

**Comment by techcoderx** [comment]
This has already been fixed a month ago [here](https://github.com/dtube/dtube/commit/147c7be3771b4c744d2042785abe045f79fae0bf).
