### ISSUE TITLE
User can't increase or decrease volume in DTube. 

### ISSUE THREAD

**Issue by ashiqurakash** [dtube/dtube#23]
Expected behavior:
User should be able to increase or decrease the volume in DTube mobile version while playing a video.

Actual behavior:
While playing a video user can't increase or decrease the volume.

How to reproduce:
1. Play a video in mobile version of DTube.
2. Try to increase or decrease the volume from the volume section given by DTube like we do in the desktop. 
3. User will be unable to do so except mute the volume.

Recorded video:
https://youtu.be/G4B3sIiWLXw

**Comment by techcoderx** [comment]
Closing this due to old issue, please recreate it if it still persists
