### ISSUE TITLE
Error while broadcasting comment edit

### ISSUE THREAD

**Issue by thedivys267** [dtube/dtube#230]
I put the wrong thumbnail to my video and attempting to edit or make the video unlisted.  Keep getting error messages.  Other error message I receive is: invalid tx data.vt

**Comment by techcoderx** [comment]
Error message clarified [here](https://github.com/dtube/avalon/commit/7bba2228b097a7fab01623ccd5939780e1e49089), vote slider should not allow 0 VP to be spent. Frontend patch coming soon.
