### ISSUE TITLE
Logged in with steem/hive - not able to vote on content

### ISSUE THREAD

**Issue by tibfox** [dtube/dtube#232]
Assuming that I don't want to have a dtube account and I am logged in with hive + steem. Then I am not able to vote on content which has been posted on all 3 chains. It always show an error message:
![Screenshot_20210117-122149_Chrome](https://user-images.githubusercontent.com/6019754/104838977-9e6e6e80-58be-11eb-940a-6543c08d29f2.jpg)

I think it would be correct that my vote can get processed on hive and steem in this case.

**Comment by molometer** [comment]
Three bugs.
Firstly I'm having the same issue with voting. Voting power vote isn't working. I can't upvotes anything? 
A second problem has appeared.
I've uploaded two videos and they never appeared on my Dtube page yet the URL links work?
Third problem. I can't edit my titles or descriptions. Server times out every time.
@molometer

**Comment by MrFasolo97** [comment]
@molometer
Do you have an avalon (dtube's blockchain) account? If you don't then it's the same problem, if you have one then you might need to wait to let your DTC build some VP and bandwidth on chain for your account (you should buy those DTC if you don't have them). It should be more clear why you can't post anyway, we should fix that.
Editing titles depends if those videos are also on dtube chain or only on hive and steem chains.
Also, we are having some problems on the API in the last days. You could try any other API except the localhost (your computer, that would need a blockchain node also) and the one you are using right now, probably the default one (avalon.d.tube).

**Comment by molometer** [comment]
MrFasolo97 
Thanks for your reply.
To answer your query.
I was logged into all three platforms Dtube, Hive and Steemit.
I'm on the Avalon blockchain.
I have 3422+ DTC plus a 300k+ of unused voting power?
These bugs started about a week or two ago? 
I didn't report it then as I know these things usually get sorted out quickly.
However:-
Not being able to edit the titles and description is a more recent bug. 
Every time I try to edit the server times out?
I shared those two videos to twitter and when you click the URL it takes you to Dtube so they are either on the blockchain or maybe in the Dtube web page cache?
Let me know of I can be of any help 
Michael 😋👍

**Comment by MrFasolo97** [comment]
As the last part of my last message, could be some problems with the API server, try switching API node under settings. Let me know if this fixes it.

**Comment by molometer** [comment]
@MrFasolo97
Thank you for your help. I switched the api to @tibfox node. It's now working fine.
