### ISSUE TITLE
invalid tx data.vt

### ISSUE THREAD

**Issue by navjot789** [dtube/dtube#233]
Each time if I upload video using **IPFS** video **CID hash** I got an ERROR **invalid tx data.vt** and cannot post the video 
![Untitled](https://user-images.githubusercontent.com/37342043/104909716-49118a80-59ae-11eb-9de4-a45f525cf375.png)

**Comment by techcoderx** [comment]
How much VP are you trying to spend? Perhaps try lowering that number slightly?

**Comment by tibfox** [comment]
@navjot789 please check the VP slider underneath the video preview in the uploader

**Comment by AbakumovAlexandr** [comment]
Jsut got the same issue. Tried setting the VP slider to various low values including 0 without any success.

**Comment by techcoderx** [comment]
Error message clarified [here](https://github.com/dtube/avalon/commit/7bba2228b097a7fab01623ccd5939780e1e49089), vote slider should not allow 0 VP to be spent. Frontend patch coming soon.

**Comment by ModApkLive** [comment]
I am also trying to upload my video on the topic [roblox mod apk download](https://modapklive.com/roblox-mod-apk/) but it is showing error "invalid tx.data.vt must be a non zero integer" as attached in screenshot below.
![Dtube Error](https://user-images.githubusercontent.com/101563734/160463758-07803d5d-d98f-4a70-ac79-1507e9891879.png)
s

**Comment by skzap** [comment]
you need to use at least 1 VP to publish a video. Move the slider a bit to the right and it will work
