### ISSUE TITLE
dTube ! Can't link/upload a second video on this site. Help please!

### ISSUE THREAD

**Issue by nikozas** [dtube/dtube#242]
invalid tx data.vt

**Comment by techcoderx** [comment]
Try reducing the number of VP to be spent in the first vote

**Comment by nikozas** [comment]
even with 0 vp       just error message invalid tx data.vt

**Comment by techcoderx** [comment]
Spending 0 VP should not be possible, the minimum required to publish a new video (or posting a new comment) is 1 VP.

**Comment by nikozas** [comment]
so i should pay some money which i dont have, to post any video?

**Comment by nikozas** [comment]
i did not know that just by pressing like button you will loose all your money

**Comment by nikozas** [comment]
so now vpn and new account or what?

**Comment by techcoderx** [comment]
VP is a non-transferable asset attached to your account. You generate 1 VP per DTC held in your account per hour. You can adjust the amount of VP to be spent in the vote using the voting slider so that you do not deplete your entire VP balance in your account.

**Comment by nikozas** [comment]
thanks for help. damn shame that i had to open new account with the different user name

**Comment by nikozas** [comment]
also on both accounts I could not add phone or facebook

**Comment by techcoderx** [comment]
You can get some DTUBEs on [Ionomy](https://exchange.ionomy.com/en/markets/btc-dtube) to start recharging some VP and bandwidth (DTUBE and DTC refer to the same token). Thanks though for discovering the voting slider error, I have fixed it [here](https://github.com/dtube/dtube/commit/75ae953278bb056701d2baaa35fbfe7c7aacc993) but changes won't be live until the next patch which I will try to get it though as soon as possible.

**Comment by techcoderx** [comment]
Error message clarified [here](https://github.com/dtube/avalon/commit/7bba2228b097a7fab01623ccd5939780e1e49089), vote slider should not allow 0 VP to be spent. Frontend patch coming soon.
