### ISSUE TITLE
Missing thumbnails on all videos

### ISSUE THREAD

**Issue by Rebelliousvoz** [dtube/dtube#247]
I come back to upload a video and I notice all my thumbnails are gone. I notice it's not just me either. 
![missing image](https://user-images.githubusercontent.com/81038543/111880081-879fd300-8966-11eb-9dde-799dae886e81.JPG)

**Comment by techcoderx** [comment]
Should be showing now, but if it happens again I've added the fallback thumbnail gateway [here](https://github.com/dtube/dtube/pull/249/commits/edca2e5876541a5a71083926d4966f97dcc61b6d).
