### ISSUE TITLE
Not uploading a thumbnail - IPFS Error while uploading - Can't upload video without thumb :(

### ISSUE THREAD

**Issue by Rebelliousvoz** [dtube/dtube#248]
I am trying to upload a video on Dtube and I am able to upload my video just fine but when I try to upload the thumbnail for the video it fail and says IPFS error while uploading. This was working fine just a week ago and I upload the thumbnail with recommended sizing 640x360.
![IPFS error](https://user-images.githubusercontent.com/81038543/111880306-021d2280-8968-11eb-96f3-644dad271636.JPG)

**Comment by techcoderx** [comment]
Thumbnail upload servers are back, but there's always https://uploader.oneloved.tube alternative IPFS/Skynet uploader if anything happens on the default servers.

**Comment by ec1oud** [comment]
This problem seems to be back: the asterisk in the upload button just keeps spinning.
