### ISSUE TITLE
DTube mobile version settings and profile option interferes each other. 

### ISSUE THREAD

**Issue by ashiqurakash** [dtube/dtube#25]
When user click on the profile icon for more option. And then click on the settings option, profile options interfere with settings. And profile options does not disappear itself after clicking on the settings icon. And also the profile options stuck open in top while user try to click on the other surface of the browser. It only disappear when user click on the profile icon again. See the recorded video for better understanding. 

Browser: Google Chrome v67.0.3396.68
Operating system: Android 7.0

Recorded video:
https://vimeo.com/274423933

**Comment by techcoderx** [comment]
Settings and logins have moved to dedicated pages since v1.0 update
