### ISSUE TITLE
Suggested improvements to Key management page UX

### ISSUE THREAD

**Issue by tangodev** [dtube/dtube#252]
The key generation/management page has some slight issues.

## 1 -- Minor issue with Dark Mode

In Dark Mode the boxes for keys and key name blend because there is no contrasting outline.

![image](https://user-images.githubusercontent.com/12778629/112551846-fdba9480-8dc1-11eb-9ea5-fc5a21259c9c.png)

## 2 -- Add explanations

The box for the key identifier should have some description like "Please name your key"

**It should be made very clear that this name will be public, so using things like legal name etc. are a no-no**.

Also, maybe let's suggest some names according to best practices?

> The friendly name for your key, so you can know what it does, ex. `upload-only-key` or `vote-only-key`.

I advise to explain to people that **the idea behind lesser authority keys is to make their accounts secure via the Least Privilege Principle**.

Another thing: what do some of those permissions do? I've been with DTube for some time and I don't know all of them. So some `i` mouse-overs are IMHO needed.

## 3 -- Link to block explorer

It may be useful to add links to the block explorer ex. "This is how others can view your account" LINK https://blocks.oneloved.tube/#/@onelovedtube

## 4 -- Identifier or name

Pet peeve: perhaps it would be better to change `identifier` for `name` or `name (a.k.a identifier)`.

**Comment by techcoderx** [comment]
The explanations can be found in the [documentation](https://d.tube/#!/wiki/faq/how-can-i-create-lesser-authority-keys) which is already linked from the keys page (the❓icon right above the master key section). Documentation needs to be updated for new tx types, however.
