### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by vpei** [dtube/dtube#258]
1.How many languages can the user set for display.
2.Users can set several video sources for display.
3.Users can customize IPFs gateway.
Hope dtube gets better and better.

**Comment by techcoderx** [comment]
1. Language preferences are in the settings, there are 38 languages available. Feel free to contribute to the translations [here](https://crowdin.com/project/dtube).
2. If you meant file sharing protocols, they can be selected by clicking on the respective logos on the top right corner of the player (if more than one mirror is available). 

<img width="84" alt="Screenshot 2021-04-05 at 7 15 57 PM" src="https://user-images.githubusercontent.com/37140751/113568656-8bf50d00-9643-11eb-8385-03c01a3c6e08.png">

3. The gateway switcher is available in the player under the settings menu.
<img width="231" alt="Screenshot 2021-04-05 at 7 18 13 PM" src="https://user-images.githubusercontent.com/37140751/113568761-c2cb2300-9643-11eb-892c-af104c40f627.png">

**Comment by vpei** [comment]
1、It's not the interface language, it's the source voice of the video.
2、Each user sets up their own gateway by default, and the gateway set up is preferred when playing video, now it is manually switch the gateway.

**Comment by vpei** [comment]
> 
> 
>     1. Language preferences are in the settings page, there are 38 languages available. Feel free to contribute to the translations [here](https://crowdin.com/project/dtube).
> 
>     2. If you meant file sharing protocols, they can be selected by clicking on the respective logos on the top right corner of the player (if more than one mirror is available).
> 
> 
> <img alt="Screenshot 2021-04-05 at 7 15 57 PM" width="84" src="https://user-images.githubusercontent.com/37140751/113568656-8bf50d00-9643-11eb-8385-03c01a3c6e08.png">
> 
>     1. The gateway switcher is available in the player under the settings menu.
> 
> 
> <img alt="Screenshot 2021-04-05 at 7 18 13 PM" width="231" src="https://user-images.githubusercontent.com/37140751/113568761-c2cb2300-9643-11eb-892c-af104c40f627.png">

1、It's not the interface language, it's the source voice of the video.
2、Each user sets up their own gateway by default, and the gateway set up is preferred when playing video, now it is manually switch the gateway.
