### ISSUE TITLE
Dtube video embed link is not working

### ISSUE THREAD

**Issue by walid321** [dtube/dtube#26]
#### Expected behavior
Dtube videos embed link is should be working so that we can embed any video from dtube and use on any website when we need.

#### Actual behavior
Dtube video embed link is not working. When i tried to embed a video from dtube, It's showing that **Unsupported**

#### How to reproduce
- Go to https://d.tube/

- Connect your steemit account with dtube.

- Then select  a video which you want to embed.

- Click on the 3 dot option which is right down on the video.

- Select **Copy Embed**

- Then you will see a green notification written here "Embed link successfully copied to your clipboard"

- Paste the embed link any other website. You can paste it to Steemit for test.

- You will see link is not working, Embed video wont be show.

* Browser/App version: Google Chrome
Version 67.0.3396.62 (Official Build) beta (32-bit)

* Operating system: Windows 10

#### Recording Of The Bug

https://youtu.be/UpmXzkYi4CU

**Comment by wehmoen** [comment]
You copied an iframe. Iframes are not allowed by Steemit and busy. If you want to share the video with your friends use the Copy Link feature. 

Use "Copy Embed" when you want to embed the video in a html page.

**Comment by tibfox** [comment]
I would love to have the possibility to embed dtube-videos on steemit as well. 
Is there any other option instead of an iframe to serve a player? Could it be the same technology like youtube doing it for that?
I can make a new issue if needed for that.

**Comment by wehmoen** [comment]
At the moment there is no way to integrate the player of a DTube video on Steemit.com. However you can create a pull request and make the required changes to add Dtube to the allowed iframe sources.
