### ISSUE TITLE
Video thumbnails are blurred

### ISSUE THREAD

**Issue by 9mido** [dtube/dtube#263]
Example:

https://d.tube/#!/c/nannal

You can only view some videos with a hover of the mouse. Shouldn't the thumbnails be unblurred?

**Comment by techcoderx** [comment]
The videos which are heavily downvoted (more VP spent on downvotes than upvotes) are blurred out by default. You can adjust it in the settings page so that they are always shown.

**Comment by 9mido** [comment]
Thanks that solved the problem.
