### ISSUE TITLE
The media could not be loaded

### ISSUE THREAD

**Issue by 9mido** [dtube/dtube#264]
"The media could not be loaded, either because the server or network failed or because the format is not supported."

After switching the gateway, that message above will appear. There is no way to switch back to another gateway once you switch and get that message. The only way is to refresh the page. 

Also, some videos just cannot be played entirely. It is in an infinite loading state and just never plays. 

Example videos:

https://d.tube/#!/v/nannal/

**Comment by techcoderx** [comment]
Videos that do not play means that no one is hosting them (or having the file pinned on at least one node) on IPFS, BTFS or Skynet. DTube does not have a central server hosting all the videos in existence as it would be cost-prohibitive as well as defeating the purpose of decentralization.

One way to reduce the chance of clicking into an unplayable video is to assign a "playability score" to each video, which might be difficult to keep the score up to date regularly 🤔
