### ISSUE TITLE
Copy stringified JSOUN in copy embed button instead of just the link

### ISSUE THREAD

**Issue by 9mido** [dtube/dtube#266]
When embedding a video on another website, the browser console shows numerous console errors. 

When loading an embedded video on a different website, it takes a while for the video embed to fully load on the site which is not desirable. 

Many console warnings are related to unsupported feature policy. 

```
Feature Policy: Skipping unsupported feature name “accelerometer”.
Feature Policy: Skipping unsupported feature name “autoplay”. 
Feature Policy: Skipping unsupported feature name “encrypted-media”. 
Feature Policy: Skipping unsupported feature name “gyroscope”.
Feature Policy: Skipping unsupported feature name “picture-in-picture”.
Feature Policy: Skipping unsupported feature name “accelerometer”. 
Feature Policy: Skipping unsupported feature name “autoplay”. 
Feature Policy: Skipping unsupported feature name “encrypted-media”. 
Feature Policy: Skipping unsupported feature name “gyroscope”. 
Feature Policy: Skipping unsupported feature name “picture-in-picture”. 

MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.
dtube.min.js:15:10183

Cookie “__cfduid” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. 
emb.d.tube
```

The network tab sometimes shows a blocked status and also an unsecure player.d.tube domain. 

Example embedded video:

https://player.d.tube/ipfs/QmZCWiZAqpQKz9xmyrXNP159deRnNxTeuvi4F7Nn1ztnNo

**Comment by techcoderx** [comment]
The "copy embed" button needs to copy the JSOUN instead of the link to skip the blockchain query on load which will speed things up
