### ISSUE TITLE
Yield farming campaign for DTC

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/dtube#269]
Get a part of the DTC treasury for rewards on staking DTC on Uniswap liquidity pools (DTC/ETH pair).

**Comment by techcoderx** [comment]
It is now possible to earn DTUBE in the DTUBE/BNB farm [here](https://d.tube/#!/farm).

**Comment by danimesq** [comment]
@techcoderx what about DTUBE/ETH and DTUBE/MATIC?
