### ISSUE TITLE
Unable to play video on dube.

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#27]
I am unable to play video on dtube.
My os- Windows 8.1
browser- Chrome Version 67.0.3396.87 (Official Build) (64-bit)
![rec-2018-06-14-12-40-39](https://user-images.githubusercontent.com/38147368/41396278-364ed646-6fd2-11e8-96b6-a8512e3b67be.gif)

**Comment by skzap** [comment]
We have been having a lot of issues past 7 days. We also moved a lot of things for video delivery so it makes sense
