### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by 9mido** [dtube/dtube#276]
Subtitles are essential for businesses/users who wish to use dtube. It is a requirement for ADA compliance. Without subtitles, businesses/users are at risk for lawsuits. 

It would be nice to have something like youtube that generates subtitles for uploaded videos automatically even if they are not accurate depictions of speech to text. Otherwise, have the option for users to upload a custom subtitle file for more speech to text accuracy. A newer fork of the autosub github project can do all of this.

**Comment by techcoderx** [comment]
VTT subtitles have been supported for years which can be uploaded by clicking on the "Add Subtitle" button.

<img width="1026" alt="Screenshot 2021-05-03 at 11 39 10 PM" src="https://user-images.githubusercontent.com/37140751/116898304-c95fb100-ac68-11eb-8d84-10fe0c35bb29.png">
