### ISSUE TITLE
Replace recaptcha with hcaptcha

### ISSUE THREAD

**Issue by 9mido** [dtube/dtube#277]
https://www.hcaptcha.com/

You could pay for hcaptcha and it does the same exact thing as recaptcha v3 invisible. Otherwise, the free version is a bit tougher to solve and more time consuming but it offers privacy and revenue to dtube.

**Comment by techcoderx** [comment]
The only service that uses captcha is the signup service, which does not belong to this repo. Unfortunately, I cannot transfer it myself as I do not have access to that repo. Therefore, please recreate it in the [correct repo](https://github.com/dtube/signup).

**Comment by 9mido** [comment]
Thanks @techcoderx I added a new issue to that repo.
