### ISSUE TITLE
HTML tags showing in some search results video descriptions

### ISSUE THREAD

**Issue by 9mido** [dtube/dtube#279]
Some videos have HTML tags showing in search result subscriptions

Example:

https://d.tube/v/clixmoney/QmRgF4PkL5tnFZbUc5uFTUw58nu1LwAmRDpJESS4mDvqdu

**Comment by techcoderx** [comment]
For this specific video, there are explicit markdown syntax in the description which is shown as expected. You can view the full details of the content in the [block explorer](https://blocks.oneloved.tube/#/content/clixmoney/QmRgF4PkL5tnFZbUc5uFTUw58nu1LwAmRDpJESS4mDvqdu).
