### ISSUE TITLE
languages and Voting and NSFW videos options tray hide when user select Esperanto language

### ISSUE THREAD

**Issue by kr-nahid** [dtube/dtube#28]
#### Expected behavior
it shouldn't be hide languages and Voting and NSFW videos options tray when user select Esperanto language in DTube mobile version .

#### Actual behavior
when user click on the languages in DTube mobile version and it open a languages tray . in the tray user should be change any language in what they want but when user select Esperanto language it hide the languages tray and nothing works when click on Voting and NSFW videos options. 

#### How to reproduce
* go to -  https://d.tube
* login with your steem account
* then click on settings and click on language 
* then select **Esperanto language** and note the bugs

> Browser : Google Chrome v67.0.3396.68
 Operating system: android 7.1.2 N2G47H

#### Recording Of The Bug
https://www.youtube.com/watch?v=t841szW1QYI

**Comment by skzap** [comment]
seems like the translation is too long there

**Comment by techcoderx** [comment]
Settings now have its own dedicated page in v1.0 update
