### ISSUE TITLE
I can't login! 

### ISSUE THREAD

**Issue by sniper1720** [dtube/dtube#281]
Hi
I just created my d.tube account but unfortunately when I try to login it keep tell me "username doesn't exist", I'm sure that the username is correct. What wrong with it?
My channel: d.tube/c/linuxtechmore21
My username: linuxtechmore21
Note: I can login in using my steem account.

**Comment by d00k13dotcom** [comment]
Username is correct and looks as if you have updated your account details 👍

![image](https://user-images.githubusercontent.com/22126613/116896132-61fe1e80-abe0-11eb-8e36-7f8cc288e46c.jpeg)

When logging in be certain you are using your DTube/Avalon keys for DTube/Avalon sign in and your Steem keys for Steem, they are not interchangeable.

If you are still facing issues feel free to reach out on the official telegram or discord.

**Comment by techcoderx** [comment]
Classical API issue that might have occurred at the time. APIs are fully functional as I'm typing this. If this happens again please switch Avalon API nodes in the settings page.
