### ISSUE TITLE
Default VP when posting / commenting should be at least 1vp

### ISSUE THREAD

**Issue by tibfox** [dtube/dtube#282]
If a user only got 10 VP and wanna post a comment / video the preselected VP will be less than 1 which results in an error message. If the preselected VP based on the user settings is less than 1 then round up to 1vp

**Comment by techcoderx** [comment]
This should have been fixed in https://github.com/dtube/dtube/commit/75ae953278bb056701d2baaa35fbfe7c7aacc993. Please provide an example where the slider still allows spending 0 VP. Closing this for now
