### ISSUE TITLE
invalid tx data.vt must be a non-zero integer

### ISSUE THREAD

**Issue by GGuljam64** [dtube/dtube#285]
When I click on Like or when I write a comment, an error such as invalid tx data.vt must be a non-zero integer is displayed, the like is not clicked, and the comment is not posted.

**Comment by techcoderx** [comment]
The error message is obvious, as you're trying to spend 0 VP on a vote which is not valid (vote sliders should not allow picking 0 VP). The minimum number of VP required for a `COMMENT`, `PROMOTED_COMMENT`, `VOTE` and `TIPPED_VOTE` operation is 1 VP.
