### ISSUE TITLE
Broke Telegram Link

### ISSUE THREAD

**Issue by d00k13dotcom** [dtube/dtube#287]
Found here
token.d.tube

![image](https://user-images.githubusercontent.com/22126613/116987929-27e25a80-ac7c-11eb-8256-64ed406af46b.jpeg)

Clicking the link

![image](https://user-images.githubusercontent.com/22126613/116988082-59f3bc80-ac7c-11eb-8eab-bd547aa308a2.jpeg)

Should go to
https://t.me/dtube_official

**Comment by DevDeckardCain** [comment]
Is this fixed?

**Comment by skzap** [comment]
https://github.com/dtube/token/commit/1da137618057291da825e1843deb73e7f39519e2
