### ISSUE TITLE
language change for refreshing page 

### ISSUE THREAD

**Issue by kr-nahid** [dtube/dtube#29]
#### Expected behavior
user should be able to stay in language which they select while in refreshing the page 

#### Actual behavior
when i select any language and it come back in English language when refreshing the page.

#### How to reproduce
* go to -  https://d.tube
* login with your steem account
* then click on settings and click on language 
* then select any language
* and close the language tray and refresh the page then note the bug

> Browser : Google Chrome v67.0.3396.68 
 Operating system: android 7.1.2 N2G47H and also windows 7 

#### Recording Of The Bug
https://www.youtube.com/watch?v=N9hLYpS_LP8

**Comment by skzap** [comment]
this is fixed in the current build and will be deployed in next production build (0.8 prob)
