### ISSUE TITLE
How long does it take for the recharge to reach my account？

### ISSUE THREAD

**Issue by vpei** [dtube/dtube#295]
https://etherscan.io/tx/0x1d2e72b6b471e77476712133cbad5b990e566ed4fbbb09a97ba70fef1ada4bda

My Account: 0 DTC    cn-vip-2020

**Comment by techcoderx** [comment]
Eth streamer crashed, should be caught up by now
https://blocks.oneloved.tube/#/tx/c9e10bafc5e9e238025307267591866e61f19cc942eaba4f271f6604898580e0
