### ISSUE TITLE
Bug: Dtube shows unknow error when tried to remove upvote/downvote

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#30]
#### Expected behavior

I expected the i will be able to remove upvote/downvote from dtube.

#### Actual behavior

I upvoted a post and tried to remove the upvote. But it dtube was showing `unknown error`.
That means either i have to downvote to remove the upvote or leave the post with the upvote.
Also can't remove downvote.

#### How to reproduce

- Login to dtube and choose any video and click on it.

- Now upvote the video. It will show you a confirmation message of upvote.

- Then try to remove the vote from the video.

- When you will again click on the like button to remove the vote dtube will show `Unknown error`

- You will face same problem in case of downvote.

* Browser version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

![Rec-2018-06-21-14-21-32.gif](https://cdn.steemitimages.com/DQmbn9e6nf2ANd3VHWA11R4kaW2pJQJyDDfhse3gSeSqCPF/Rec-2018-06-21-14-21-32.gif)

**Comment by skzap** [comment]
It should clearly remove the vote if you click again on it. Will get this fixed

**Comment by techcoderx** [comment]
Now with Avalon, once a vote is cast it may not be removed nor changed unless leaders decided to allow this in a hardfork
