### ISSUE TITLE
Cannot submit comments

### ISSUE THREAD

**Issue by Biggly** [dtube/dtube#300]
On any video, if I try to comment I get "Invalid tx data vt must be a non-zero integer"

**Comment by Biggly** [comment]
(I should add Windows 7, with Vivaldi browser)

**Comment by zmi1** [comment]
+1

**Comment by tibfox** [comment]
@Biggly @zmi1 please check that your vp amout you (have to) use for comments is greater than 0: 
![grafik](https://user-images.githubusercontent.com/6019754/123912078-df45d580-d97c-11eb-87bd-e63826f75708.png)
![grafik](https://user-images.githubusercontent.com/6019754/123912207-08666600-d97d-11eb-8e36-15b478006895.png)

Every comment / post needs to have at least 1 VP

**Comment by DevDeckardCain** [comment]
Can this be closed?

**Comment by Biggly** [comment]
I have "20 VP"

0 DTC whatever that is. 

Still cannot comment, get ""Invalid tx data vt must be a non-zero integer". Note it says 'vt" not VP.

**Comment by techcoderx** [comment]
In the early days it used to be `vt` but it has been renamed to VP to better reflect the fact that they are not transferrable. Just ensure that at least 1 VP is spent in the vote/comment.

**Comment by techcoderx** [comment]
Closing this, if you still have any issues please contact us on #q-and-a on the official Discord server
