### ISSUE TITLE
Any limit for user to upload videos?

### ISSUE THREAD

**Issue by nzhl** [dtube/dtube#302]
I absolutely a newbie about dtube, block chain and the decentralized tech underneatch, i am wondering how can dtube delete those unwanted videos i.e. those anti-social or anti-hunmans if dtube is running on the top of the blockchain ? 

It's kinda of a paradox for me to let everyone upload content freely and keep them uncensorable while having mechanism for deleting some unwanted content.

**Comment by DevDeckardCain** [comment]
As far as I understand, there isnt a way for them to remove the video, they just hide it so that people can't search for it and it won't get recommended.

However, this discussion should really happen on a wiki or something, and this discussion should be closed as its not an issue.
