### ISSUE TITLE
Original content option does nothing

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/dtube#305]
If it does nothing, then I feel like it should either start doing something, or be removed. It sends conflicting messages about what leadership wants from the DTube community.

**Comment by techcoderx** [comment]
This is a declaration that so far only indicates so in a boolean value in the JSON metadata. The original plan is to use this as a filter option and perhaps a requirement by certain curation groups. See #137 for more info.

**Comment by DevDeckardCain** [comment]
I guess we won't discuss it then.
