### ISSUE TITLE
OneLove IPFS Uploader - Access Denied

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/dtube#308]
When selecting the uploader.oneloved.tube, it opens an error bubble in the top right with an access denied error.

Pics or it didn't happen - > https://imgur.com/a/O6rABuc

**Comment by techcoderx** [comment]
Please DM me the transaction ID if you have paid and still getting the same error after sufficient confirmations (14 blocks for DTUBE, 21 blocks for STEEM and HIVE).

**Comment by DevDeckardCain** [comment]
> Please DM me the transaction ID if you have paid and still getting the same error after sufficient confirmations (14 blocks for DTUBE, 21 blocks for STEEM and HIVE).

Ohhh, this is the paid service? The blurb says its free :P
