### ISSUE TITLE
Bug Dtube : After changing the language in EEsti language, language list looks only half and unclear.

### ISSUE THREAD

**Issue by zaid222** [dtube/dtube#31]
#### Expected behavior
Supposedly when I want to change the language in EESTI language, all features including language features should be displayed clearly

#### Actual behavior
When I use english all the features look clear, and when I change the language in EESTI language, and then I press the language feature to change it again, but the language list looks only half and unclear.

#### How to reproduce
* Open Google chrome
* Serching Dtube
* Login use a steemconnect
* Click settings
* Click languanges
* Select languanges EEsti
* See bug
>Browser: GoogleChrome v.67.0.3396.87
Operating system: Android 6.0

Recording of the bug
https://m.youtube.com/watch?v=jYhlUop_Sd8

**Comment by techcoderx** [comment]
It's probably not well translated, feel free to contribute to translations at https://crowdin.com/project/dtube
