### ISSUE TITLE
IPFS Error while uploading thumbnail

### ISSUE THREAD

**Issue by illtellyoulater** [dtube/dtube#312]
Hello, I'm a new DTube user. I've been trying for about an hour to upload a short video (10 Mb) but when I try to upload the thumbnail it takes ages and in the end it says "IPFS Error while uploading thumbnail".

Things I've tried: 
- make the thumbnail size exactly the recommended size (640x360 px)
- convert the image to JPG format
- convert the image to PNG format

and none of the above worked.
Is there something I am doing wrong or is this a bug?

After some googling I found that this looks like a recurring problem, for example see: 

- https://steemkr.com/dtube/@offgridlife/help-with-dtube-upload-ipfs-error-while-uploading-snap-photo
- https://steemit.com/help/@paulsmuts/oycile98
- https://steemit.com/dtube/@themoneygps/dtube-upload-problems-has-anyone-seen-this

Could you please help? It's really sad to see such a powerful platform failing to work because of a quirk like this.
Thanks.

**Comment by DevDeckardCain** [comment]
> Hello, I'm a new DTube user. I've been trying for about an hour to upload a short video (10 Mb) but when I try to upload the thumbnail it takes ages and in the end it says "IPFS Error while uploading thumbnail".
> 
> Things I've tried:
> 
>     * make the thumbnail size exactly the recommended size (640x360 px)
> 
>     * convert the image to JPG format
> 
>     * convert the image to PNG format
> 
> 
> and none of the above worked.
> Is there something I am doing wrong or is this a bug?
> 
> After some googling I found that this looks like a recurring problem, for example see:
> 
>     * https://steemkr.com/dtube/@offgridlife/help-with-dtube-upload-ipfs-error-while-uploading-snap-photo
> 
>     * https://steemit.com/help/@paulsmuts/oycile98
> 
>     * https://steemit.com/dtube/@themoneygps/dtube-upload-problems-has-anyone-seen-this
> 
> 
> Could you please help? It's really sad to see such a powerful platform failing to work because of a quirk like this.
> Thanks.

Hello! We've been having some issues with the thumbnail uploader. What I'm suggesting until this gets resolved, is to upload your video to Youtube as an unlisted video (or public, if you prefer), then "upload" the Youtube video to DTube, but before you click publish, you can click "Add Video" to add your IPFS content ;)

I have an in-depth video on DTube here: https://d.tube/v/devdeckardcain94/QmWR2hXJ78gAjwwenvQX7fWHPmjo4DvhrPLLuWACHe1bye
You can also reach out on Discord: DeckardCain#9887


Side Note: Fear not! This platform isn't going anywhere. I'm rather new here, but keep an eye on my repos for new computer programs / features for DTube
