### ISSUE TITLE
There are a bunch of rabid dogs among the administrators of d.tube

### ISSUE THREAD

**Issue by vpei** [dtube/dtube#316]
You have a group of mad dogs in your administrator, as long as the point of view is different from theirs, as long as others post videos, they use many small numbers to step on, this group of mad dogs do not drive away, your site can not be developed.

**Comment by crypt0inf0** [comment]
@vpei This is not related to dtube issue. Please express your thought on https://discord.com/channels/347020217966395393/347020218796736512

**Comment by tibfox** [comment]
@techcoderx @skzap can someone please close this?

**Comment by skzap** [comment]
Can you name the rabid dogs? Are you saying this because you got downvoted? Can you please also link your dtube profile?

**Comment by techcoderx** [comment]
Re-closing this, please report any abuse in #report-abuse in official Discord server
