### ISSUE TITLE
Dtube- Playback Rates Doesn't Fit Video Screen

### ISSUE THREAD

**Issue by realrufans** [dtube/dtube#32]
#### Expected behavior
Video playback rates was suppose to fit the screen

#### Actual behavior
The playback rate options is too large on mobile device
![IMG-20180621-WA0002.jpg](https://cdn.steemitimages.com/DQmSr57KfSuyx9CEYoVdME52xC6G2wUnHn7UiXv3tb6RwXt/IMG-20180621-WA0002.jpg)

#### How to reproduce
 * Go to [Dtube](https://d.tube)
* Click on any available video to play
* Click on the video settings icon
* Click on playback rate

* Browser/App version: Chrome 67.0.3396.87
* Operating system: Android 0

#### Recording Of The Bug
https://youtu.be/DQZHYjigy9c

**Comment by skzap** [comment]
This is related to the player. Please re-open the issue in https://github.com/dtube/embed/issues

**Comment by realrufans** [comment]
Okay thank you
