### ISSUE TITLE
Allow IPFS bafy hash 

### ISSUE THREAD

**Issue by brishtiteveja** [dtube/dtube#321]
Allow IPFS bafy hash (from CID 0 -> CID 1)
Check docs: https://docs.ipfs.io/concepts/content-addressing/#cid-conversion

**Comment by brishtiteveja** [comment]
May be not needed.

**Comment by techcoderx** [comment]
Base32 CIDv1 is the newer standard that some gateways exclusively use (such as `dweb.link`) and is generally used when hashes cannot be case sensitive. The newer versions of IPFS API uses it IIRC.
