### ISSUE TITLE
No linked named v

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/dtube#327]
Once we moved to IPFS I've been seeing a lot of strange issues. The most recent; which was first reported by: famigliacurione, is as follows:

famigliacurione — Today at 11:33 AM
@techcoderx [NOT DTube team] Hey Bro! Hope you are doing well! I uploaded a video today with One Love and got this strange message once the video was loaded.

ipfs resolve -r /ipfs/bafybeiaxy5dtw6t2zkoiqrvukrdpswjb73pasux5ucnvee2aqtw6sf5e4e/v/famigliacurione/QmdsQoDqvJS1w6E5R7iZdWyCu7QGcek5wGyc3JKDiikiEq: no link named "v" under bafybeiaxy5dtw6t2zkoiqrvukrdpswjb73pasux5ucnvee2aqtw6sf5e4e

The video was uploaded to DTube without any problems, but since I never saw this message before I thought to report it to you as it may be a bug.

You can easily reproduce this issue by middle clicking on a video to open it in a new tab:

https://imgur.com/a/2JQ0wyl

**Comment by brishtiteveja** [comment]
I saw this same error .. multiple times.

**Comment by techcoderx** [comment]
Pinning this and marking as super high priority as many links posted everywhere are now broken

**Comment by DevDeckardCain** [comment]
Someone fixed this but didn't close the issue.

**Comment by skzap** [comment]
I moved back to github hosting as Fleek (IPFS) was 'down'. The issue hasn't properly been resolved and might come back next time GitHub bans us.
