### ISSUE TITLE
Bug : when giving a low vote on the post, an unknown error occurred and failed to vote

### ISSUE THREAD

**Issue by zaid222** [dtube/dtube#33]
#### Expected behavior
I should be able to vote with a vote of any vote 1-100% vote, but when I vote with a low vote of 1-6%, an unexpected error occurs when voting.

#### Actual behavior
when voting on a post with a sound value of 1-6%, there was an unknown error at the time, but if I give a value of 8-100% of the vote, the vote was successful done

#### How to reproduce
* Open Google chrome
* Serching Dtube
* Login use a steemconnect
* Click settings and then select features @vote and then select the lowest vote value
* Next, vote on a post
* See bug
> Browser: GoogleChrome v.67.0.3396.87
Operating system: Android 6.0

#### Recording of the bug
https://m.youtube.com/watch?v=uh8z7nOGVYY

**Comment by skzap** [comment]
which account are you using and how much steem power do you have on it?

**Comment by sourovafrin** [comment]
I don't think this problem is from dtube's end.
May be you had tested, with a low sp account.
Steemit don't allow to vote such low weight to littler sp holder.

**Comment by techcoderx** [comment]
Dust votes are allowed post HF20, also the newer Avalon blockchain allows voting with as little as 1 VP
