### ISSUE TITLE
Invalid tx data.vt must be non-zero integer

### ISSUE THREAD

**Issue by Pak-Ameen** [dtube/dtube#339]
I am a novice to this side of the Internet, not having any content-provider experience not any coding.

When I discovered D-TUBE, I undertook registration and attempted to upload a first video which I made for my English SL pupils.
But then, after filing all required fields and being ready to publish, I got a message which I cannot solve on the very upload screen.

IT SAYS: Invalid tx data.vt must be non-zero integer

After searching everywhere for a field that required me to insert an integer I had to pass.
Please, a kind soul may be out somewhere, help me. D-TUBE does not have a helpdesk email anywhere and redirects to an FAQ that leaves it to me to PUT IN SEARCH QUERIES based on "non-zero integer" and its manifold variations, but also there I can't find anything, which is quite disappointing considering that this is a platform that makes money, too.

Some guidance, please, maybe by email. My students should have time to rehearse the song until Saturday.

**Comment by brishtiteveja** [comment]
You do not have voting power yet because you do not have enough Dtube coin (DTC) in your account. What is your username on dtube? Me or other leaders can send you some DTC. 1 DTC generates VP every hour for you and soon you will be able to post. We had to restrict this way to prevent spammers. Thank you.

**Comment by techcoderx** [comment]
Closing this, if you are still facing this issue please find us on Discord linked above
