### ISSUE TITLE
Bug: Dtube account automatically logged out from login when reloaded the page.

### ISSUE THREAD

**Issue by walid321** [dtube/dtube#34]
#### Expected behavior

Dtube should be logged in after reloading the page when steemit account already logged in on dtube.

#### Actual behavior

dtube automatically logged out from log in , when the dtube site is reloaded.

#### How to reproduce

- Login to dtube

- When you will access your dtube account, then reload the page.

- Press **Ctrl + R**  to reload the page.

- You will see your dtube account automatically logged out from login.

* Browser version:  Chrome Version 68.0.3440.33 (Official Build) beta (32-bit)

* Operating system: Windows 10

#### Recording Of The Bug
https://youtu.be/aRT14G7WaZs

**Comment by skzap** [comment]
what the fuck? Are you dumb? There's a fucking 'remember me' thing RIGHT ON THE LOGIN PAGE.

This is not a bug

**Comment by akbarbadsha360** [comment]
@skzap mind your language!
I think you don't know how to speak anyone.
You language identified your family as a stupid.
