### ISSUE TITLE
DTUBE- The Amount Of Subscribers Decrease As Subscriber's Tab Is Frequently Tapped

### ISSUE THREAD

**Issue by realrufans** [dtube/dtube#35]
#### Expected behavior
Once a profile Subscriber's tab is clicked, it was expected to display the list of the user's subscribers.

#### Actual behavior
It was noticed that the amount of subscribers decreases to a point If the Subscribers tab is frequently clicked.

**BEFORE CLICKING**
![IMG-20180623-WA0001.jpg](https://cdn.steemitimages.com/DQmNa8nXZHtANKLqAjcgcek5izSZxLnnyBmKbgrerthMEmo/IMG-20180623-WA0001.jpg)

**AFTER CLICKING**
![IMG-20180623-WA0000.jpg](https://cdn.steemitimages.com/DQmXjgniCAgdhADrrTBFwX2b51gcYZhYCm1ZXgcY3rojnAf/IMG-20180623-WA0000.jpg)

#### How to reproduce
 * Go to [Dtube](https://d.tube)
* Click on any available profile
* Continuously  click on the user's subscribers

* Browser/App version: Chrome 67.0.3396.87
* Operating system: Android 0

#### Recording Of The Bug
https://youtu.be/oUuftkWfSl4

**Comment by techcoderx** [comment]
A bit of an old issue as it is now on its own chain
