### ISSUE TITLE
Can't claim DTC

### ISSUE THREAD

**Issue by Nakaza994** [dtube/dtube#359]
I have some claimable DTC that apparently doesn't want to be claimed.

It sits there for a couple of seconds then gives this error message:

![image](https://user-images.githubusercontent.com/115698120/195549711-9fc841fd-159f-4cf0-a572-9daf9a7fcb00.png)

Any help?

**Comment by techcoderx** [comment]
Avalon crashed due to unknown issue in one transaction that can't be traced back, producers are working to get it back up
