### ISSUE TITLE
In case of multiple account uses Dtube automatically switch to first account when any page of dtube is reloaded

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#36]
#### Expected behavior

Dtube allows to add multiple accounts.
I expected that, i will be able to use all of them as the first one.

#### Actual behavior

I had added 2 accounts on dtube.
But when i was using my second account and i reloaded a page on dtube, it automatically switched my account to first one.

#### How to reproduce

- Firstly add 2 accounts on dtube

- Now switch your account to second one, it will switch your account within a moment.

- After switching to your second account, reload the page. You can do it from any page of dtube, it is not compulsory to reload on the landing page after account switching

- You will see that dtube automatically switched your account to first one.

* Browser version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

![rec-2018-06-23-13-56-57](https://user-images.githubusercontent.com/38147368/41807710-b25440d6-76f4-11e8-9752-4f1bb225702f.gif)

**Comment by techcoderx** [comment]
Multi-account login with the same network was replaced by multi-network login since Avalon and Hive integration
