### ISSUE TITLE
Dtube cannot load IPFS video [SOLVED]

### ISSUE THREAD

**Issue by qdhj** [dtube/dtube#371]
Maybe it's a problem on my side, then I politely ask to help me. So, I'm uploading a video to IPFS (through IPFS Desktop) correctly compressed in H264 (format: .mp4), pinning it, publishing to IPNS, etc. Still, when I try to upload it to Dtube (through CID/hash), I get an error: "**The media could not be loaded, either because the server or network failed or because the format is not supported**" - already in redactor, as well as if i publish it. The video is accessible from IPFS gate (eg. https://ipfs.io/), but not from Dtube.

![image](https://user-images.githubusercontent.com/122599546/229347326-f1104b02-1222-41c6-b185-debcb6ff1cf3.png)

*****************************************

**SOLVE:** 

Use another gateway!

![image](https://user-images.githubusercontent.com/122599546/233606220-a39dcae2-4223-4c1c-be17-1532ecb77a59.png)

So it would look like this:

![image](https://user-images.githubusercontent.com/122599546/233604738-a34928bf-847d-49a2-8584-29cd5973fded.png)

**Comment by MrFasolo97** [comment]
I'm not sure we support IPNS (maybe publish IPFS CID a.k.a hash directly, not going through IPNS), but anyway, you should try to change the gateway that DTube is using on the bottom-right corner of the video (if I recall correctly) to something else, like ipfs.io, as the old upload server and gateway (player.d.tube I guess) is offline for a while now, we're working on a new upload and storage option with its own gateway lately.
