### ISSUE TITLE
Last vote time shows wrong info as it is effected by posting instead of vote cast

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#38]
#### Expected behavior

Dtube should show exact time info of last upvote cast on `About` section

#### Actual behavior

Dtube is showing wrong last vote time.
It should changed time with vote casting. But vote cast doesn't effect the time of **Last Vote** instead authoring post is effecting it.
**Last Vote time** is showing last posted time.

#### How to reproduce

- Firstly vote on a post (You can do it from any front end)

- Now check you last time vote info on `About`section of profile.

- You will observe that it didn't effect last vote time.

- Now create a post then again check `About` and now you will see that vote time has been changed though u didn't vote anyone.

* Browser version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

![rec 2018-06-25 11 58 27](https://thumbs.gfycat.com/ForthrightAgonizingDungbeetle-size_restricted.gif)
See it on big window [here](https://gfycat.com/gifs/detail/ForthrightAgonizingDungbeetle).

**Comment by techcoderx** [comment]
There is no more "last vote time" since Avalon was developed
