### ISSUE TITLE
Videos on Custom IPFS Gateway Do Not Play

### ISSUE THREAD

**Issue by cahlenlee** [dtube/dtube#381]
I upload videos via the command line using my own IPFS Gateway (ipfs.cahlen.org). My videos stopped playing several days ago, even the ones uploaded previously that had been working.

Example:
https://d.tube/#!/v/cahlen/sleeping-on-a-cot

Did something get changed which would affect custom gateway videos?

**Comment by MrFasolo97** [comment]
Hi, I've checked the web console on your video and I saw this:
`emb.d.tube/#!//('files':('ipfs':('vid':('src':'bafybeiejemopoqdbfzvns27gmxbbaqwcp7c36bljm7kllzl4pfrwdhmivq'),'img':('118':'bafkreih3fhd7ijpbdd2sm2rskfno7wbslgqz5w75o2gp6w4osimc4z7krq','360':'bafkreih3fhd7ijpbdd2sm2rskfno7wbslgqz5w75o2gp6w4osimc4z7krq'),'gw':'https:!!ipfs.cahlen.org')),'dur':165,'nsfw':0,'oc':1,'thumbnailUrl':'https:!!ipfs.d.tube!ipfs!bafkreih3fhd7ijpbdd2sm2rskfno7wbslgqz5w75o2gp6w4osimc4z7krq')/true/true/IPFS:1 Access to XMLHttpRequest at 'https://ipfs.cahlen.org/ipfs/bafybeiejemopoqdbfzvns27gmxbbaqwcp7c36bljm7kllzl4pfrwdhmivq' from origin 'https://emb.d.tube/' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*,*', but only one is allowed.`
Looks like a problem with CORS setting on your server, probably you specified twice the * as Access-Control-Allow-Origin, or maybe just once and something is adding the second one, I guess you're using a reverse proxy, like Nginx maybe?
Let me know if you find a fix for it. If you need further help you can DM me on discord and we could take a look together, anyway, I'm pretty busy lately, so my replies might not be fast. Good luck.

**Comment by cahlenlee** [comment]
Thanks, I was able to solve the problem with that info!
