### ISSUE TITLE
Dtube is not showing action link for replied and unvoted option on activity tab

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#40]
#### Expected behavior

On Dtube, it should show action link for all options on activity tab.
There are many option like voted, resteemed, replied, subscribed, unvoted, unsubscribed etc.
All of these should show link of the action.

#### Actual behavior

On Dtube , replied and unvoted options are not showing it's action link.
But others are showing. Like when we upvote or your are upvoted you will see the link of the post on voted activity. When you subscribe anyone, it will show user name. By clicking on the username you will be able to visit user's profile.But in case of replied and unvote option it is not showing link and for this reason we are unable to visit the action.

#### How to reproduce

- Login Dtube with private posting key.

- Now go to your profile and click on activity

- You will see many option, now check mark **voted** from filter. It will show vote action, and you will see links are showing for it. Same in case of others without replied and unvoted.

- Now unmark all and only check mark **replied** and **unvote** . Thought it will show activity but won't show link to it's action.

* Browser version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

![rec-2018-06-28-08-48-33](https://user-images.githubusercontent.com/38147368/42073262-4ad72404-7b87-11e8-9595-e04c001d2436.gif)

**Comment by techcoderx** [comment]
this should not be an issue with the current activities tab that lists activities from the Avalon account
