### ISSUE TITLE
Dtube is not showing video length on preview when a specific tag is selected from trending tags

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#42]
#### Expected behavior

We can generally see the video length on video preview.
I expected that i will be able to see video length on all video preview.

#### Actual behavior

When user select a specific tag from trending section, it takes user to trending page of dtube and shows those videos with that specific tag.
Though Dtube shows video length on preview but was not showing video length on that page.

#### How to reproduce

- Login Dtube with private posting key.

- Now you will see many option on left side. You will find trending tags there.

- Select random one and it will take you to trending page where you will see videos only with that specific tag.

- But you will see that none of those videos are showing the length of the video.

* Browser version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

![rec-2018-06-29-10-48-46](https://user-images.githubusercontent.com/38147368/42122184-9e1dcd42-7c5f-11e8-8e1b-32fd4f5b8987.gif)

**Comment by techcoderx** [comment]
fixed in #249
