### ISSUE TITLE
Uploading videos from local host using ipfs

### ISSUE THREAD

**Issue by cryptodev90** [dtube/dtube#43]
The documentation regarding IPFS says - "Then simply point upload.js to localhost:5000 instead of our production encoding servers."

Where do i find the upload.js file?

**Comment by skzap** [comment]
I was referring to this file: client/views/pages/upload/upload.js

However I accepted a change in a pull request recently that moved this option simply to the settings. To achieve the same, just go to client/settings.js and change localhost to true and it should point on localhost:5000 for local uploads. Feel free to reach out on discord if you need help with the ipfs-uploader
