### ISSUE TITLE
Upload hundreds of videos easily?

### ISSUE THREAD

**Issue by hellomotow** [dtube/dtube#44]
I was wondering if there is a script to upload loads of videos easily? For example

./program -sourcevideohash Q321St4cU3........... -snap '/root/previews/video 1 test.jpg' -videotitle 'This is a test' -nsfw y/n  -description -tag etc

**Comment by skzap** [comment]
No. I do not want to prioritize things like that especially currently through our centralized upload servers. If you do it through your own ipfs node then it should be okay.

Also the STEEM blockchain has a limitation of 5 minutes between each root post, so you won't ever be able to go faster than that.

**Comment by hellomotow** [comment]
@skzap I will be doing it through my own IPFS node which is why I added the "-sourcevideohash Q321St4cU3" part.

The images will go through your servers but if there is a way to do it with my own IPFS hash I'm all for it.

**Comment by skzap** [comment]
https://github.com/dtube/dtube/blob/master/client/views/pages/upload/uploadform/uploadform.js#L74

**Comment by techcoderx** [comment]
Now with Avalon you're limited to account bandwidth, so unless you have a lot of DTCs to generate them in a short period of time this is not possible
