### ISSUE TITLE
Markdown is not working properly on Dtube

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#45]
#### Expected behavior

Markdown helps to make posts great.
I expected that Markdown will work on Dtube. It should work on both post and comment.

#### Actual behavior

Markdown is not working on dtube in bot post and comment case.

#### How to reproduce

- Login Dtube with private posting key.

- Now find out a post which used markdown.

- Or do a comment on a random video using markdown.

- You will see that it is appearing as a usual text.

* Browser version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

![dtube-bug](https://user-images.githubusercontent.com/38147368/42409418-0f5a4354-81fc-11e8-8367-9b1d4e8dd71e.gif)

**Comment by dhimmel** [comment]
@sourovafrin did you close this because markdown support has been added (but not deployed) or is markdown support still missing?

I especially care about comments where users expect markdown to work. Users leave comments from a variety of clients and most of them use markdown.

**Comment by sourovafrin** [comment]
@dhimmel i don't remember why i did close the issue. But i hope they will deploy soon.
