### ISSUE TITLE
Dtube 0.7 - Dtube is Auto Logout When User Close the Browser

### ISSUE THREAD

**Issue by sabbir1213** [dtube/dtube#46]
### Expected behavior
Dtube Should Don't Auto Logout when user's Close Theirs Browser.I expected that Dtube Do not Logout without User's Permission.It should work for all users.

### Actual behavior
I had Login My Account on Dtube.
But When I use Dtube and after some time I close my browser then i follow that When again open dtube then dtube wanna again login approval for me. I Think It's really annoying at too much for every single user.

### How to reproduce
- First time You login on dtube with private posting key.
- Then Some time You use dtube.
- Then you close your browser.
- Then again browse https://d.tube When you will see that dtube want to you again login approval.
- Browser version: Mozila Firefox 61.0.1 (64-bit)
- Operating system: Windows 7 Professional

### Recording Of The Bug
https://youtu.be/oGAGYJz3ba0

**Comment by techcoderx** [comment]
Remember me is now checked by default
