### ISSUE TITLE
Dtube 0.7 - Dtube search bar's search icon is not clickable 

### ISSUE THREAD

**Issue by sabbir1213** [dtube/dtube#47]
### Expected behavior
Search bar's Search Icon should Clickable. I expected that dtube Search bar's search icon should clickable, then user get help for search any topic.

### Actual behavior
Dtube Search bar's Search icon is Not Clickable. Dtube Search bar's search icon should be clickable because many user don't have no keyboard some time when they are face problem for search any topic in dtube. Now user can't search any topic without keyboard enter button.

### How to reproduce
- Login dtube with private posting key.
- Write something is dtube search bar and try to click search bar's search icon.
- Its not clickable, when you need keyboard enter button.
- Browser version: Mozilla Firefox 61.0.1 (64-bit)
- Operating system: Windows 7 Professional.

### Recording Of The Bug 
https://youtu.be/cjRYzjkFQK0

**Comment by skzap** [comment]
search has been fixed on v0.9, our new blockchain supports elastic search mirroring through 'monstache'.
