### ISSUE TITLE
Dtube creates duplicate account section if user try to login same account through steemconnect

### ISSUE THREAD

**Issue by sourovafrin** [dtube/dtube#51]
#### Expected behavior

Dtube should not able user to login an account which is already logged in like the manual login method-

![Screenshot_4.png](https://cdn.steemitimages.com/DQmVxt9hsD2wR5niaeKegguiqtnuPKgvaXmXaoSgNBNiqYB/Screenshot_4.png)

If user try to login one account twice through steemconnect dtube should return it to the first one and should not create duplicate of it.

#### Actual behavior

If there is an account logged in and user again try to login the same account through steemconnect, dtube creates duplicate of it instead of returning to the first account. Dtube reacts as it is different account and make another section for the same account.

#### How to reproduce

- Go on dtube and login an account (you can use both login method)

- After being logged in try to add another account clicking on `Add another account`

- It will take you to login page, this time choose steemconnect as your login method

- Now try to login the same account which is already logged in.

- You will see that it dtube caught it as different account and made another section for it.

- You can try to login multiple time. It will create duplicate everytime.

* Browser version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

![rec-2018-07-13-00-34-42](https://user-images.githubusercontent.com/38147368/42682730-36e1ef98-86ad-11e8-9f85-41cd22f69ac7.gif)

**Comment by techcoderx** [comment]
SteemConnect was depreciated in v0.8 update
