### ISSUE TITLE
Video by ID and default player src

### ISSUE THREAD

**Issue by palbergstrom** [dtube/dtube#55]
Sorry if this is the wrong place for a question but I wonder if there is a default iframe src that I can use when I only have the video ID in dtube?

Example https://d.tube/v/pressfortruth/wpbgu72y would be something like https://d.tube/player/wpbgu72y

**Comment by skzap** [comment]
No you cannot. The identifier for videos is the author + the permlink

The permlink alone isn't unique, two different users could use the same one

**Comment by palbergstrom** [comment]
Thank you. That's my answer for ID: author + the permlink. Obvious if I used my brain.
