### ISSUE TITLE
can not start dtube 

### ISSUE THREAD

**Issue by shuinan** [dtube/dtube#61]
I install dtube successfuly  at unbuntu 16.04 and  start with "meteor -p 3333", all are ok.
but, the page turn to https://xxxx:3333 when I open  http://xxxx:3333. and show "Can not access this web site".
How can I do ?

**Comment by chinobaingo** [comment]
I have the same issue. Did you ever resolve?

**Comment by techcoderx** [comment]
it can be accessed through http://localhost:3333 for that port argument
