### ISSUE TITLE
d.tube search problem

### ISSUE THREAD

**Issue by zerkoth** [dtube/dtube#64]
So, even if your video is called like "Black Clover XXXXX" you can't find it just by typing black clover in the search window. I don't know why but i tried on diffrent devices and without an account. (My first thought was i just can't find my own videos).
Is it a bug or i'm just making something wrong?

**Comment by Katamori** [comment]
AFAIK DTube utilized a 3rd party service for searching - that feature is yet to be solved.

**Comment by skzap** [comment]
search has been fixed on v0.9, our new blockchain supports elastic search mirroring through 'monstache'.
