### ISSUE TITLE
"Unknown error" on posting a video

### ISSUE THREAD

**Issue by hazae41** [dtube/dtube#65]
I can't post any video on DTube
I get "unknown error"
https://youtu.be/HNNkG_3pXOQ

**Comment by grigio** [comment]
I confirm I get:

```
Failed to load https://v2.steemconnect.com/api/broadcast: Response for preflight is invalid (redirect)
```

**Comment by techcoderx** [comment]
SteemConnect login was depreciated since 0.8. Closing this
