### ISSUE TITLE
Automated upload?  API?

### ISSUE THREAD

**Issue by k-k-k-ken** [dtube/dtube#67]
Hi, I am working on Perl code to automate uploading a video.

Unfortunately, I can't use WWW::Mechanize, due to the JavaScript that creates the login form.

So, I've learned Selenium::Firefox, and managed to login.

However, now I'm stuck: I can't send_keys() to the id="fileToUpload".  So then I tried "clicking" on it, which does bring up the file chooser dialog -- but, then can't send keys to that dialog (and, I'm on Ubuntu 16.04 and will ultimately be launching Firefox headlessly).

Before throwing up my hands and declaring defeat, wanted to ask: is there an API?  Has anyone else written code to automated the process of uploading a video?  (Can I use some "JavaScript magic" to make the "fileToUpload" input element be a text box which I can then send_keys() to?)

Thanks!

**Comment by k-k-k-ken** [comment]
Oh, forgot to add: I saw #44 but it's asking for "hundreds of videos" -- I just want to automate a single upload.  Thanks again!

**Comment by wehmoen** [comment]
All you need to to is to create a steem post with the correct json_metadata fields.
Upload your video to ipfs and put the hashes in there :)
![image](https://user-images.githubusercontent.com/6608103/46912012-618ed100-cf6b-11e8-8a42-ee367378a1ba.png)
