### ISSUE TITLE
How to modify the gateway 

### ISSUE THREAD

**Issue by wg1929** [dtube/dtube#7]
How to modify the gateway because ipfs.io China cannot access

**Comment by wg1929** [comment]
You did not think seriously about this answer. I certainly have no problem with myself. But what about others? I can't ask everyone to install this

**Comment by qwertychouskie** [comment]
Use Tor/a VPN.

**Comment by wg1929** [comment]
modify the gateway

**Comment by kirkins** [comment]
@wg1929 why don't you make a live fork of dtube with a different gateway.

Why should the rest of the internet change because your country is an oppressive dictatorship censoring the internet?

**Comment by wg1929** [comment]
Are you funny? My first sentence has already asked how to revise the gateway, or you can not understand the words of others?

**Comment by wg1929** [comment]
@kirkins  how to revise the gateway

**Comment by kirkins** [comment]
@wg1929 I think you can do a search in the source code for `ipfs.io` then replace that with an alternative gateway. Here is a [list of alternative gateways](https://ipfs.github.io/public-gateway-checker/).

Info from related issues on IPFS repo:

https://github.com/ipfs/go-ipfs/issues/4765

https://github.com/ipfs/community/issues/290

**Comment by kirkins** [comment]
Might need other changes not sure never ran this locally. Hopefully the info can help you in getting started.

**Comment by bostrot** [comment]
@kirkins i bet they are all banned in china.
changing all ipfs links to one of the gateways should be enough.

**Comment by skzap** [comment]
This app only controls the pictures. So if you remove ipfs.io and only use snap.d.tube for pictures, it should work. If you want videos to load through another gateway for the videos, you will need to edit the player: https://github.com/dtube/embed

Changing to another gateway will probably not be a good solution as it would end up with this new gateway being banned in your country in the future. The only real change that can happen, is implementing js-ipfs into our player for direct loading (without gateway).

**Comment by wg1929** [comment]
I modified the player，But how do you install it?...

**Comment by wg1929** [comment]
@skzap I modified the player，But how do you install it?...

**Comment by skzap** [comment]
in `client/views/commons/videos/player.js`, just change emb.d.tube for your own modified player !

**Comment by wg1929** [comment]
@skzap    Or modify this   https://github.com/dtube/production

**Comment by skzap** [comment]
Yes the player is a static application too. You can host it on github pages directly and it will give you https://wg1929.github.io/embed link that you can use.

**Comment by wg1929** [comment]
@skzap   Ok, thank you very much

**Comment by arni077** [comment]
@bostrot Does integrating IPFS daemon in a browser will make every person who use this browser to surf freely in any ipfs website without the influence of any existing ban(for example: china ban) ?

**Comment by bostrot** [comment]
Well you don't integrate an IPFS daemon in a browser. You normally create a server with it and then, yes, everyone who has access to this server can access the gateway.

If you are on mobile you can use the app I made which is available on Google Play and the App Store: https://github.com/bostrot/DTubeViewer where the ipfs gateway can be customized.

**Comment by techcoderx** [comment]
Gateway switcher was added to the embed payer, pull request [here](https://github.com/dtube/embed/pull/30), video demo [here](https://dtube.techcoderx.com/#!/v/techcoderx/QmcMm92bxgRHbDdMsZDANyvQNf9328covEZ1YZF47L2UcM).
