### ISSUE TITLE
Bug: getting empty grey rectangle when opening a video using ipfs-go

### ISSUE THREAD

**Issue by skliarie** [dtube/dtube#70]
I use IPFS companion and ipfs-go 0.4.17 (ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub --writable)

If I disable IPFS companion, then video opens. If I use IPFS Companion, then I get empty grey rectangle.

Debug tool shows that it sent some IPFS request and is pending on it.

If I disable IPFS Companion, then the request Status is shown as "(canceled)" after 47 ms and almost does not affect loading speed.

**Comment by techcoderx** [comment]
IPFS has improved significantly over the last few updates in terms of content discovery, so videos should load faster from the IPFS network using a local daemon.
