### ISSUE TITLE
Is there an API for Retrieving DTube Mp4s?

### ISSUE THREAD

**Issue by AdamSHurwitz** [dtube/dtube#74]
Hi DTube Community,

I'm building an Android app to discover and organize crypto tech news across, text, audio, and video and creating a customized suggestion engine. I would like to explore integrating Dtube content.  I am searching the documentation in order to see **how to query for videos as well as obtain their mp4s** so that I can play videos from the Android client with ExoPlayer.

Much appreciated!

**Comment by techcoderx** [comment]
You can use the Steem API to obtain the IPFS hash from a DTube post, then build the video link.

the link would be https://video.dtube.top/ipfs/$hash for videos stored on DTube's servers, and https://cloudflare-ipfs.com/ipfs/$hash if the video is not present on their servers.

**Comment by ilyaigpetrov** [comment]
> You can use the Steem API to obtain the IPFS hash from a DTube post,

@techcoderx, could you, please, guide us on how to do this 1) on a low-performance device and 2) in an censorship resistant way (so we can't use any DNS domains)? Should I compile my own steemd for an low-end arm rpi zero device and use wallet cli with it?

**Comment by skzap** [comment]
A bit old issue. We moved to our own blockchain now. We also support more than IPFS now, also BTFS and Sia Skynet.

But you can get the full data for a video by using any avalon api node with /content/<author>/<video_id>

https://avalon.d.tube/content/techcoderx/QmZXj7bRg8WchtMiE8JaC454FiiMQEAdbNC9tnE8uApsrR
https://avalon.oneloved.tube/content/techcoderx/QmZXj7bRg8WchtMiE8JaC454FiiMQEAdbNC9tnE8uApsrR
https://avalon.tibfox.com/content/techcoderx/QmZXj7bRg8WchtMiE8JaC454FiiMQEAdbNC9tnE8uApsrR

If you run a node locally:
http://localhost:3001/content/techcoderx/QmZXj7bRg8WchtMiE8JaC454FiiMQEAdbNC9tnE8uApsrR

Notice also how the source hash will be the identifier of the video (in most cases)
