### ISSUE TITLE
[Feature Request] Markdown interpreter

### ISSUE THREAD

**Issue by Jzarecta** [dtube/dtube#76]

**Comment by wehmoen** [comment]
Like this
![image](https://user-images.githubusercontent.com/6608103/56087873-40ecf880-5e74-11e9-8792-0d7ff2ca1ceb.png)
?
I have done this for a dtube clone in the past. If it is this what you want i can surely integrate it into dtube.

**Comment by Jzarecta** [comment]
Great.. lets get it done. Although this is more for the 'body' of the video post more than the comments IMO.
