### ISSUE TITLE
My video isn't found although I have uploaded it on dtube

### ISSUE THREAD

**Issue by bidetaggle** [dtube/dtube#78]
My video is Clog #1 - By my eyes and the research bar doesn't find it. As well there is nothing to search profiles. Could you explain me why?

**Comment by skzap** [comment]
search has been fixed on v0.9, our new blockchain supports elastic search mirroring through 'monstache'.

**Comment by bidetaggle** [comment]
I search "Clog" i have "There is result for Clog", then a blank page.
I should find at least this one https://d.tube/#!/v/bidetaggle/t9cobji0
