### ISSUE TITLE
how Dtube video search works

### ISSUE THREAD

**Issue by LastExile16** [dtube/dtube#80]
Hello,
I couldn't find any guideline about dtube, can you explain how the dtube finds videos without any server?

**Comment by wehmoen** [comment]
Unfortunately a blockchain has no search function. When Asksteem was shutdown there was no real alternative for DTube. The team is still trying to figure out the best way to handle search requests and video suggestion.

**Comment by skzap** [comment]
New blockchain has support for elastic search mirroring of contents and accounts! Check it out on https://github.com/dtube/avalon
