### ISSUE TITLE
Video upload appears to work but does not populate video hash fields

### ISSUE THREAD

**Issue by dhimmel** [dtube/dtube#81]
I have started experiencing an issue recently where my DTube uploads fail. I can drag the video file into the upload box, which then does an initial upload with the progress bar. After the upload completes the video box looks like:

> ![image](https://user-images.githubusercontent.com/1117703/50490662-49601700-09dc-11e9-895e-5a49f8e185c8.png)

Note that it is a little wonky in dimensions and I cannot use the position slider to navigate through the video. The advanced info looks like:

> ![image](https://user-images.githubusercontent.com/1117703/50490677-5b41ba00-09dc-11e9-9d92-1a527b12f833.png)

Notice how the IPFS hashes are not auto-populated. If I click submit, I get the error message:

> Please upload a video before submitting.

I don't see any obvious error messages in my Chrome browser's console.

**Comment by dhimmel** [comment]
In firefox the video frame shows:

> No video with supported format and MIME type found.

This is odd because in the past I've uploaded videos that with the same format and encoding, such as https://d.tube/#!/v/monstertalk/lmzputke.

**Comment by dhimmel** [comment]
I used handbrake to convert from .mkv to .m4v, (reducing the resolution to 1080) and then upload was successful. Video online at https://d.tube/#!/v/monstertalk/cp3pl2uc. In any case, DTube should provide an error message on what aspect of my original encoding was not supoerted.

**Comment by dhimmel** [comment]
Just uploaded https://d.tube/#!/v/monstertalk/00bx6zq2 without issue. I switched the recording software to use .mp4 rather than .mkv, so I guess this issue may be that DTube does not support MKV format and does not provide a clear error message in this case?

**Comment by techcoderx** [comment]
Video uploads have changed significantly since then, so closing this for now
