### ISSUE TITLE
AskSteem has been discontinued.

### ISSUE THREAD

**Issue by fredddier** [dtube/dtube#82]
Search feature is not working anymore, AskSteem has been [discontinued](https://steemit.com/asksteem/@thekyle/asksteem-is-shutting-down) since January 1st, 2019.

**Comment by FredoGonzalezR** [comment]
AskSteem [seems](https://steemit.com/asksteem/@thekyle/re-beggars-re-thekyle-asksteem-is-shutting-down-20181212t081430882z) to be already working with DTube to solve it.

**Comment by FredoGonzalezR** [comment]
It seems that this repo is inactive.

**Comment by FredoGonzalezR** [comment]
@jens1o Reopened issue but has not been solved since then. Though this project is no longer maintained.

**Comment by skzap** [comment]
We have now replaced AskSteem with the 'monstache' feature of https://github.com/dtube/avalon. See the readme about it. This is what we are using to power the new search since 0.9
