### ISSUE TITLE
search results empty, channel's video tab empty

### ISSUE THREAD

**Issue by sashaman** [dtube/dtube#84]
win 10 pro x64, firefox, waterfox as well as chrome all show an empty page 
https://d.tube/#!/c/sempervideo   -> empty page 
FIX: add the closing slash at end of address
https://d.tube/#!/c/sempervideo/

dunno why but i hope this gets fixed asap as this is **VERY** annoying
greetings

**Comment by damiantoczek** [comment]
There is a fetch error in the console.
Must be a database call that prob checks if there are any videos, if not...
This should be showed (line 3):
https://github.com/dtube/dtube/blob/master/public/DTube_files/lang/en/en-US.json

**Comment by sashaman** [comment]
still?? wtf
browsing to 
https://d.tube/#!/c/sempervideo -> no videos shown/listed
fix: add trailing slash
https://d.tube/#!/c/sempervideo**/**

**Comment by skzap** [comment]
search has been fixed on v0.9, our new blockchain supports elastic search mirroring through 'monstache'.
