### ISSUE TITLE
Videos aren't loaded when local ipfs node is active

### ISSUE THREAD

**Issue by bitphage** [dtube/dtube#85]
I'm using "IPFS Companion" browser extension and working local ipfs node (127.0.0.1:8080). When I'm trying to access any video, it doesn't load. In js console I have the following messages:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
415e3dd8e067517d27694fec6b9e1a81d8192595.js:139 Error: API not responding!
api.coinmarketcap.com/v1/ticker/STEEM-DOLLARS/:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
415e3dd8e067517d27694fec6b9e1a81d8192595.js:139 Error: API not responding!
415e3dd8e067517d27694fec6b9e1a81d8192595.js:139 Loaded languages
/#!/v/denniskoray/4v4qitvu:1 Access to fetch at 'https://api.asksteem.com/related?author=denniskoray&permlink=4v4qitvu&include=meta%2Cpayout&q=created%3A%3E%3D2019-02-05%20AND%20meta.video.info.title%3A*' from origin 'https://d.tube' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
/#!/v/denniskoray/4v4qitvu:1 Uncaught (in promise) TypeError: Failed to fetch
415e3dd8e067517d27694fec6b9e1a81d8192595.js:139 Loaded video from chain Object
/#!/v/denniskoray/4v4qitvu:1 Access to fetch at 'https://api.asksteem.com/trending?q=meta.video.info.title%3A*%20AND%20created%3A%3E%3D2019-01-13&types=tags&size=50' from origin 'https://d.tube' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
/#!/v/denniskoray/4v4qitvu:1 Uncaught (in promise) TypeError: Failed to fetch
```

If I disable "IPFS Companion" the video is loading properly.

**Comment by wehmoen** [comment]
ERR_BLOCKED_BY_CLIENT => 
https://meta.stackexchange.com/questions/223764/what-are-these-errors-about-in-the-chrome-console-when-visiting-stackoverflow#comment729536_223764

**Comment by bitfag** [comment]
I disabled adblock, but it didn't help. Also updated chromium browser. That "TypeError" looks suspicious.

```
Access to fetch at 'https://api.asksteem.com/trending?q=meta.video.info.title%3A*%20AND%20created%3A%3E%3D2019-01-14&types=tags&size=50' from origin 'https://d.tube' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
(index):1 Uncaught (in promise) TypeError: Failed to fetch
/#!/v/dcooperation/h5y5ul5d:1 Access to fetch at 'https://api.asksteem.com/related?author=dcooperation&permlink=h5y5ul5d&include=meta%2Cpayout&q=created%3A%3E%3D2019-02-06%20AND%20meta.video.info.title%3A*' from origin 'https://d.tube' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
/#!/v/dcooperation/h5y5ul5d:1 Uncaught (in promise) TypeError: Failed to fetch
415e3dd8e067517d27694fec6b9e1a81d8192595.js:139 Loaded video from chain Object
```

**Comment by wehmoen** [comment]
https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present

Google is a awesome invention!

**Comment by SouthernWolf95** [comment]
> If I disable "IPFS Companion" the video is loading properly.

This is definitely an issue on my end as well. When I have the IPFS Companion plugin running in my browser the videos won't load at all and multiple errors are thrown in the console. Here's an example of what a page looks like:
![Screen Shot 2019-04-11 at 12 24 10 AM](https://user-images.githubusercontent.com/22421310/55930692-80a3ae00-5bf0-11e9-9a8a-9e6b2ce5a0b8.png)
 And here are the errors that get thrown in the console:
![Screen Shot 2019-04-11 at 12 26 00 AM](https://user-images.githubusercontent.com/22421310/55930703-92855100-5bf0-11e9-972d-41630172d5d8.png)

I'm not sure what is causing these issues, but I think it would definitely be advantageous for D.Tube to support using this plugin or at least work cleanly with it. Many people have discovered IPFS through using D.Tube, including myself, and are very likely going to be using the plugin since it's recommended by IPFS as a clean way of interacting with the network.

**Comment by wehmoen** [comment]
Most errors are related to Asksteem. You can ignore those :) 
There are a couple of extensions that causes issues with either the DTube website or the playback of videos. I use IPFS Companion myself and have no problems. Do you have any other addons installed?
