### ISSUE TITLE
[Feature-request] Define a field for default IPFS gateway in the content JSON

### ISSUE THREAD

**Issue by vaultec81** [dtube/dtube#90]
Videos uploaded on d.tube should be stamped with a special signature. This would allow a front end or other system to use the correct gateway from where the video was uploaded. I have something similar on dtube network, where the stamp in json_meta app, however when people edit this on steemit.com or d.tube it disrupts the signature. Could use another element. I think its important and removes inefficient system such as a head request to video.dtube.top then use ipfs.io if that fails.

**Comment by wehmoen** [comment]
Cant you put a watermark on the thumbnail?

**Comment by skzap** [comment]
I think @vaultec81 is suggesting adding a new field in the JSON we write on the blockchain to reference the default/canonical IPFS gateway to use for the player. It's true that if we knew on which gateway the file is actively hosted, we would reduce the loading times, and distribute the load more evenly.

Maybe @nannal will have a different opinion though

**Comment by techcoderx** [comment]
Already added in the latest update of uploader UI
