### ISSUE TITLE
Unable to access front end

### ISSUE THREAD

**Issue by chinobaingo** [dtube/dtube#99]
After install cannot access localhost:3000 due to SSL error

Cannot access from external IP

So I started meteor with:
Meteor -p 185.177.59.222:8080

It says apprunning at: http://185.177.59.222:8080

When I access  it from external box it redirects the HTTP to HTTPS and the “Dtube” favicon loads but says “ERR_CONNECTION_CLOSED”

So basically I have no way to actually access the page after install and app is running...

How to access machine from external box (I’m running this on a VPS)

Thanks?

**Comment by danielj86** [comment]
Having the same issue

**Comment by skzap** [comment]
Try using `ROOT_URL=http://localhost:3000` when starting the meteor dev server.
